(defpackage :lab.theorem-workbench
  (:use :cl)
  (:import-from :lab.math
                #:math-proof-problem
                #:math-object-id
                #:compile-math-search-formal-bridge
                #:discharge-math-search-formal-bridge)
  (:export
   #:*theorem-statuses*
   #:theorem-target
   #:make-theorem-target
   #:theorem-target-id
   #:theorem-target-statement
   #:theorem-target-domain-id
   #:theorem-target-semantic-ref
   #:theorem-target-status
   #:theorem-target-representations
   #:theorem-target-provenance
   #:theorem-target-metadata
   #:theorem-statement
   #:make-theorem-statement
   #:theorem-statement-id
   #:theorem-statement-premises
   #:theorem-statement-conclusion
   #:theorem-statement-domain-id
   #:theorem-statement-provenance
   #:theorem-statement-metadata
   #:theorem-status
   #:make-theorem-status
   #:theorem-status-target-ref
   #:theorem-status-status
   #:theorem-status-witness-refs
   #:theorem-status-obstruction-refs
   #:theorem-status-execution-trace-ref
   #:theorem-status-search-trace-ref
   #:theorem-status-metadata
   #:theorem-search-policy
   #:theorem-search-policy-id
   #:theorem-search-policy-allowed-operator-families
   #:theorem-search-policy-budget
   #:theorem-search-policy-metadata
   #:theorem-witness
   #:theorem-witness-id
   #:theorem-witness-target-ref
   #:theorem-witness-kind
   #:theorem-witness-payload
   #:theorem-witness-scope
   #:theorem-witness-trace-ref
   #:theorem-witness-metadata
   #:theorem-obstruction
   #:theorem-obstruction-id
   #:theorem-obstruction-target-ref
   #:theorem-obstruction-kind
   #:theorem-obstruction-witness
   #:theorem-obstruction-scope
   #:theorem-obstruction-trace-ref
   #:theorem-obstruction-metadata
   #:theorem-search-trace
   #:theorem-search-trace-id
   #:theorem-search-trace-target-ref
   #:theorem-search-trace-source-state-ref
   #:theorem-search-trace-operator-ref
   #:theorem-search-trace-candidate-ref
   #:theorem-search-trace-metadata
   #:theorem-execution-trace
   #:theorem-execution-trace-id
   #:theorem-execution-trace-target-ref
   #:theorem-execution-trace-projection-ref
   #:theorem-execution-trace-provider-ref
   #:theorem-execution-trace-result
   #:theorem-execution-trace-metadata
   #:theorem-domain-adapter
   #:make-theorem-domain-adapter
   #:theorem-domain-adapter-id
   #:theorem-domain-adapter-compile-target-fn
   #:theorem-domain-adapter-generate-candidate-fn
   #:theorem-domain-adapter-project-obligations-fn
   #:theorem-domain-adapter-check-candidate-fn
   #:theorem-domain-adapter-extract-counterexample-fn
   #:theorem-domain-adapter-render-status-fn
   #:theorem-domain-adapter-render-report-fn
   #:theorem-domain-adapter-metadata
   #:register-domain
   #:find-domain
   #:list-domains
   #:register-target
   #:find-target
   #:list-targets
   #:register-definition
   #:find-definition
   #:register-operator-family
   #:find-operator-family
   #:compile-target
   #:generate-candidate
   #:project-obligations
   #:check-candidate
   #:extract-counterexample
   #:render-status
   #:render-report
   #:topology-status->theorem-status
   #:topology-target-row->theorem-target
   #:run-theorem-workbench-tests))
