(load (merge-pathnames "load-lab.lisp" *load-truename*))
(load (merge-pathnames "integration.lisp" *load-truename*))
(load (merge-pathnames "phase-model.lisp" *load-truename*))
(in-package :vm9-lab)
(let* ((inputs (list :source-ref (or (uiop:getenv "VM9_SOURCE_REF") (fail "missing source ref"))
                     :evidence-ref (or (uiop:getenv "VM9_EVIDENCE_REF") (fail "missing evidence ref"))
                     :binding-sha256 (or (uiop:getenv "VM9_BINDING_SHA256") (fail "missing binding"))))
       (path (or (uiop:getenv "VM9_ENVELOPE") (fail "missing envelope path")))
       (mode (or (uiop:getenv "VM9_MODE") (fail "missing mode")))
       (candidate (cond ((string= mode "produce") (make-candidate inputs))
                        ((string= mode "restore") (read-envelope path))
                        (t (fail "unknown mode")))))
  (recheck-envelope candidate inputs)
  (when (string= mode "produce") (write-envelope path candidate))
  (format t "VM9 LAB PHASE MODEL ACCEPTED: 2 native, 2 reference, 13 residual OPEN; ~A~%" mode))
