(load (merge-pathnames "load-lab.lisp" *load-truename*))
(load (merge-pathnames "integration.lisp" *load-truename*))
(load (merge-pathnames "phase-model.lisp" *load-truename*))
(in-package :vm9-lab)
(let* ((original (uiop:getenv "VM9_ENVELOPE"))
       (directory (pathname (uiop:getenv "VM9_FAULT_DIRECTORY"))))
  (dolist (mutation '(:unproved :digest :assumption :stale :authority))
    (let ((envelope (read-envelope original)))
      (case mutation
        (:unproved (setf (k::certificate-term (first (refinement-envelope-model-certificates envelope)))
                         (k::zero-term)))
        (:digest (setf (k::certificate-env-digest (first (refinement-envelope-model-certificates envelope)))
                       :wrong-environment))
        (:assumption (setf (residual-obligation-assumptions (first (refinement-envelope-residuals envelope))) nil))
        (:stale (setf (getf (refinement-envelope-inputs envelope) :binding-sha256) "stale"))
        (:authority (setf (refinement-envelope-authority envelope) :proved)))
      (write-envelope (merge-pathnames (format nil "~(~A~).sexp" mutation) directory) envelope))))
