(defpackage :lab.math
  (:use :cl)
  (:export
   #:*math-expression-operators*
   #:*math-statuses*
   #:math-expression
   #:math-expression-op
   #:math-expression-args
   #:math-expression-value
   #:math-expression-name
   #:math-expression-metadata
   #:make-math-expression-v1
   #:math-expression-key
   #:math-definition
   #:math-definition-id
   #:math-definition-expression
   #:math-definition-domain-ref
   #:math-definition-provenance
   #:math-definition-metadata
   #:make-math-definition-v1
   #:math-domain
   #:math-domain-id
   #:math-domain-name
   #:math-domain-parent-refs
   #:math-domain-constraints
   #:math-domain-provenance
   #:math-domain-metadata
   #:make-math-domain-v1
   #:math-claim
   #:math-claim-id
   #:math-claim-statement
   #:math-claim-expression
   #:math-claim-domain-ref
   #:math-claim-hypotheses
   #:math-claim-status
   #:math-claim-dependencies
   #:math-claim-provenance
   #:math-claim-metadata
   #:make-math-claim-v1
   #:math-theorem
   #:math-theorem-id
   #:math-theorem-claim
   #:math-theorem-status
   #:math-theorem-proof-receipt-ref
   #:math-theorem-dependencies
   #:math-theorem-provenance
   #:math-theorem-metadata
   #:make-math-theorem-v1
   #:math-hypothesis
   #:math-hypothesis-id
   #:math-hypothesis-statement
   #:math-hypothesis-expression
   #:math-hypothesis-domain-ref
   #:math-hypothesis-status
   #:math-hypothesis-provenance
   #:math-hypothesis-metadata
   #:make-math-hypothesis-v1
   #:math-bound
   #:math-bound-id
   #:math-bound-subject
   #:math-bound-relation
   #:math-bound-bound
   #:math-bound-domain-ref
   #:math-bound-provenance
   #:math-bound-metadata
   #:make-math-bound-v1
   #:math-asymptotic
   #:math-asymptotic-id
   #:math-asymptotic-lhs
   #:math-asymptotic-relation
   #:math-asymptotic-rhs
   #:math-asymptotic-limit
   #:math-asymptotic-domain-ref
   #:math-asymptotic-provenance
   #:math-asymptotic-metadata
   #:make-math-asymptotic-v1
   #:math-transform
   #:math-transform-id
   #:math-transform-kind
   #:math-transform-input
   #:math-transform-output
   #:math-transform-domain-ref
   #:math-transform-provenance
   #:math-transform-metadata
   #:make-math-transform-v1
   #:math-counterexample
   #:math-counterexample-id
   #:math-counterexample-target-claim-ref
   #:math-counterexample-witness
   #:math-counterexample-backend
   #:math-counterexample-scope
   #:math-counterexample-failed-assumptions
   #:math-counterexample-provenance
   #:math-counterexample-metadata
   #:make-math-counterexample-v1
   #:math-proof-problem
   #:math-proof-problem-id
   #:math-proof-problem-target-claim
   #:math-proof-problem-representation
   #:math-proof-problem-allowed-operator-classes
   #:math-proof-problem-policy
   #:math-proof-problem-provenance
   #:math-proof-problem-metadata
   #:make-math-proof-problem-v1
   #:math-equivalence
   #:math-equivalence-id
   #:math-equivalence-left-ref
   #:math-equivalence-right-ref
   #:math-equivalence-forward-ref
   #:math-equivalence-reverse-ref
   #:math-equivalence-status
   #:math-equivalence-provenance
   #:math-equivalence-metadata
   #:make-math-equivalence-v1
   #:math-no-go
   #:math-no-go-id
   #:math-no-go-strategy
   #:math-no-go-assumptions
   #:math-no-go-failure-result-ref
   #:math-no-go-counterexample-ref
   #:math-no-go-target-refs
   #:math-no-go-provenance
   #:math-no-go-metadata
   #:make-math-no-go-v1
   #:math-object-id
   #:math-object-status
   #:*lab-formal-native-operation-allowlist*
   #:math-formal-native-claim
   #:math-formal-native-claim-formal-operation-id
   #:math-formal-native-claim-formal-args
   #:math-formal-native-claim-target-proposition
   #:math-formal-native-claim-trusted-boundary
   #:make-math-formal-native-claim-v1
   #:register-default-math-formal-projection-laws
   #:math-formal-projection-law
   #:make-math-formal-projection-law
   #:math-formal-projection-law-id
   #:math-formal-projection-law-source-claim-class
   #:math-formal-projection-law-supported-domain
   #:math-formal-projection-law-target-backend
   #:math-formal-projection-law-translator
   #:math-formal-projection-law-target-proposition-builder
   #:math-formal-projection-law-trusted-boundary
   #:math-formal-projection-law-reconstruction-description
   #:math-formal-projection-law-unsupported-behavior
   #:math-formal-projection-law-version
   #:register-math-formal-projection-law
   #:find-math-formal-projection-law
   #:list-math-formal-projection-laws
   #:clear-math-formal-projection-laws
   #:math-formal-projection
   #:math-formal-projection-id
   #:math-formal-projection-projection-law-ref
   #:math-formal-projection-source-claim-ref
   #:math-formal-projection-target-backend
   #:math-formal-projection-target-proposition
   #:math-formal-projection-payload
   #:math-formal-projection-trusted-boundary
   #:math-formal-projection-supported-p
   #:math-formal-projection-diagnostics
   #:project-math-claim
   #:math-provider
   #:make-math-provider
   #:math-provider-id
   #:math-provider-trust-class
   #:math-provider-supported-claim-classes
   #:math-provider-candidate-input-schema
   #:math-provider-result-schema
   #:math-provider-certificate-type
   #:math-provider-counterexample-type
   #:math-provider-cost-class
   #:math-provider-replay-semantics
   #:math-provider-executor
   #:register-math-provider
   #:find-math-provider
   #:list-math-providers
   #:initialize-default-math-providers
   #:math-provider-result
   #:math-provider-result-provider-id
   #:math-provider-result-status
   #:math-provider-result-evidence
   #:math-provider-result-certificate
   #:math-provider-result-counterexample
   #:math-provider-result-trusted-boundaries
   #:math-provider-result-diagnostics
   #:invoke-math-provider
   #:math-search-formal-bridge
   #:make-math-search-formal-bridge
   #:math-search-formal-bridge-id
   #:math-search-formal-bridge-status
   #:math-search-formal-bridge-candidate-ref
   #:math-search-formal-bridge-math-claim-ref
   #:math-search-formal-bridge-operator-ref
   #:math-search-formal-bridge-source-state-ref
   #:math-search-formal-bridge-projection
   #:math-search-formal-bridge-metadata
   #:compile-math-search-formal-bridge
   #:discharge-math-search-formal-bridge
   #:research-graph-math-bridge
   #:make-research-graph-math-bridge
   #:research-graph-math-bridge-source-system
   #:research-graph-math-bridge-source-logical-id
   #:research-graph-math-bridge-source-object-id
   #:research-graph-math-bridge-math-object-id
   #:research-graph-math-bridge-direction
   #:research-graph-math-bridge-provenance
   #:research-expression->math-expression
   #:research-proof-object->math-object
   #:math-object->research-record
   #:math-claim->lsip-search-wire-v1
   #:math-proof-problem->lsip-search-wire-v1
   #:math-subsumption-result-v1
   #:math-subsumption-result-v1-status
   #:math-subsumption-result-v1-proof-effect
   #:math-subsumption-v1
   #:math-theorem-match-v1
   #:math-theorem-match-v1-conclusion-status
   #:math-theorem-match-v1-hypothesis-statuses
   #:match-math-theorem-v1
   #:math-asymptotic-relation-v1
   #:math-asymptotic-relation-v1-proof-effect
   #:make-math-asymptotic-relation-v1
   #:dominant-balance-v1
   #:dominant-balance-v1-status
   #:make-dominant-balance-v1
   #:math-experiment-v1
   #:math-experiment-v1-proof-effect
   #:make-math-experiment-v1
   #:complete-math-experiment-v1
   #:math-falsification-result-v1
   #:math-falsification-result-v1-status
   #:math-falsification-result-v1-witness
   #:math-falsification-result-v1-proof-effect
   #:make-math-falsification-result-v1
   #:math-falsification-provider-v1
   #:math-falsification-provider-v1-provider-ref
   #:make-math-falsification-provider-v1
   #:register-math-falsification-provider-v1
   #:run-math-falsification-pipeline-v1
   #:finite-integer-falsification-executor-v1
   #:make-finite-integer-falsification-provider-v1
   #:analytic-side-condition-v1
   #:analytic-side-condition-v1-kind
   #:analytic-side-condition-v1-proof-effect
   #:analytic-side-conditions-for-transformation-v1
   #:saddle-analysis-v1
   #:saddle-analysis-v1-status
   #:saddle-analysis-v1-proof-effect
   #:make-saddle-analysis-v1
   #:run-formal-math-tests))
