(in-package :mini-kernel)

(defun proof-example-type ()
  (mk-pi (nat-type)
         (eq-term (nat-type)
                  (mk-var 0)
                  (mk-var 0))))

(defun proof-example-term ()
  (mk-lam (nat-type)
          (refl-term (nat-type) (mk-var 0))))

(defun nat-reduction-demo-term ()
  (app* (mk-const 'add)
        (list (zero-term)
              (succ-term (zero-term)))))

(defun run-demo ()
  (let* ((env (make-bootstrap-env))
         (proof-term (proof-example-term))
         (proof-type (proof-example-type))
         (nat-demo (nat-reduction-demo-term))
         (nat-target (succ-term (zero-term))))
    (validate-environment env)
    (check env '() proof-term proof-type)
    (unless (conv? env '() nat-demo nat-target)
      (kernel-error "nat-rec demo did not reduce as expected"))
    (format t "bootstrap declarations validated~%")
    (format t "proof term checked: ~S~%" proof-term)
    (format t "proof type: ~S~%" proof-type)
    (format t "nat reduction demo: ~S == ~S~%" nat-demo nat-target)
    t))
