(in-package :mini-kernel)

(defun json-object-get (object key)
  (cdr (assoc key object :test #'string=)))

(defun json-whitespace-char-p (char)
  (member char '(#\Space #\Tab #\Newline #\Return) :test #'char=))

(defun json-skip-whitespace (text index)
  (loop while (and (< index (length text))
                   (json-whitespace-char-p (char text index)))
        do (incf index)
        finally (return index)))

(defun json-parse-string (text index)
  (unless (char= (char text index) #\")
    (kernel-error "expected JSON string at index ~D" index))
  (incf index)
  (let ((out (make-string-output-stream)))
    (loop
      (when (>= index (length text))
        (kernel-error "unterminated JSON string"))
      (let ((char (char text index)))
        (incf index)
        (cond
          ((char= char #\")
           (return (values (get-output-stream-string out) index)))
          ((char= char #\\)
           (when (>= index (length text))
             (kernel-error "unterminated JSON escape"))
           (let ((escape (char text index)))
             (incf index)
             (write-char
              (case escape
                (#\" #\")
                (#\\ #\\)
                (#\/ #\/)
                (#\b #\Backspace)
                (#\f #\Page)
                (#\n #\Newline)
                (#\r #\Return)
                (#\t #\Tab)
                (otherwise
                 (kernel-error "unsupported JSON escape: ~C" escape)))
              out)))
          (t
           (write-char char out)))))))

(defun json-parse-number (text index)
  (let ((start index))
    (when (char= (char text index) #\-)
      (incf index))
    (loop while (and (< index (length text))
                     (digit-char-p (char text index)))
          do (incf index))
    (values (parse-integer text :start start :end index) index)))

(defun json-parse-literal (text index literal value)
  (let ((end (+ index (length literal))))
    (unless (and (<= end (length text))
                 (string= literal text :start1 0 :end1 (length literal)
                          :start2 index :end2 end))
      (kernel-error "expected JSON literal ~A at index ~D" literal index))
    (values value end)))

(defun json-parse-array (text index)
  (unless (char= (char text index) #\[)
    (kernel-error "expected JSON array at index ~D" index))
  (incf index)
  (let ((items '()))
    (loop
      (setf index (json-skip-whitespace text index))
      (when (>= index (length text))
        (kernel-error "unterminated JSON array"))
      (when (char= (char text index) #\])
        (incf index)
        (return (values (nreverse items) index)))
      (multiple-value-bind (value next-index)
          (json-parse-value text index)
        (push value items)
        (setf index (json-skip-whitespace text next-index))
        (cond
          ((char= (char text index) #\,)
           (incf index))
          ((char= (char text index) #\])
           (incf index)
           (return (values (nreverse items) index)))
          (t
           (kernel-error "expected JSON array delimiter at index ~D" index)))))))

(defun json-parse-object (text index)
  (unless (char= (char text index) #\{)
    (kernel-error "expected JSON object at index ~D" index))
  (incf index)
  (let ((pairs '()))
    (loop
      (setf index (json-skip-whitespace text index))
      (when (>= index (length text))
        (kernel-error "unterminated JSON object"))
      (when (char= (char text index) #\})
        (incf index)
        (return (values (nreverse pairs) index)))
      (multiple-value-bind (key next-index)
          (json-parse-string text index)
        (setf index (json-skip-whitespace text next-index))
        (unless (char= (char text index) #\:)
          (kernel-error "expected JSON object ':' at index ~D" index))
        (incf index)
        (setf index (json-skip-whitespace text index))
        (multiple-value-bind (value value-index)
            (json-parse-value text index)
          (push (cons key value) pairs)
          (setf index (json-skip-whitespace text value-index))
          (cond
            ((char= (char text index) #\,)
             (incf index))
            ((char= (char text index) #\})
             (incf index)
             (return (values (nreverse pairs) index)))
            (t
             (kernel-error "expected JSON object delimiter at index ~D" index))))))))

(defun json-parse-value (text index)
  (setf index (json-skip-whitespace text index))
  (when (>= index (length text))
    (kernel-error "unexpected end of JSON input"))
  (let ((char (char text index)))
    (cond
      ((char= char #\")
       (json-parse-string text index))
      ((char= char #\{)
       (json-parse-object text index))
      ((char= char #\[)
       (json-parse-array text index))
      ((or (char= char #\-) (digit-char-p char))
       (json-parse-number text index))
      ((char= char #\t)
       (json-parse-literal text index "true" t))
      ((char= char #\f)
       (json-parse-literal text index "false" nil))
      ((char= char #\n)
       (json-parse-literal text index "null" :null))
      (t
       (kernel-error "unsupported JSON value at index ~D" index)))))

(defun read-json-file (path)
  (with-open-file (stream path :direction :input)
    (let ((text (with-output-to-string (out)
                  (loop for line = (read-line stream nil nil)
                        while line
                        do (write-string line out)
                           (write-char #\Newline out)))))
      (multiple-value-bind (value index)
          (json-parse-value text 0)
        (setf index (json-skip-whitespace text index))
        (unless (= index (length text))
          (kernel-error "trailing JSON data in ~A at index ~D" path index))
        value))))
