(defpackage :mini-kernel-kernel-spec-tests
  (:use :cl)
  (:export #:run-tests))

(in-package :mini-kernel-kernel-spec-tests)

(define-condition test-failure (error)
  ((message :initarg :message :reader test-failure-message))
  (:report (lambda (condition stream)
             (princ (test-failure-message condition) stream))))

(defun fail-test (format-string &rest args)
  (error 'test-failure :message (apply #'format nil format-string args)))

(defmacro is-equal (expected form)
  `(let ((expected-value ,expected)
         (actual-value ,form))
     (unless (equal expected-value actual-value)
       (fail-test "expected ~S, got ~S from ~S"
                  expected-value
                  actual-value
                  ',form))))

(defmacro is-true (form)
  `(unless ,form
     (fail-test "expected truthy form: ~S" ',form)))

(defun run-test (name thunk)
  (handler-case
      (progn
        (funcall thunk)
        (format t "ok   ~A~%" name)
        t)
    (error (condition)
      (format t "FAIL ~A~%  ~A~%" name condition)
      nil)))

(defun test-check-frozen-kernel-spec-kr ()
  (let* ((spec (mini-kernel:make-frozen-kernel-core-spec))
         (results (mini-kernel:check-kernel-spec-kr spec))
         (summary (mini-kernel:summarize-kernel-spec-results results)))
    (is-equal 6 (getf summary :total))
    (is-equal 4 (getf summary :accepted))
    (is-equal 2 (getf summary :rejected))
    (is-equal 6 (getf summary :matched))
    (is-equal 0 (getf summary :mismatched))))

(defun test-check-frozen-kernel-spec-kl ()
  (let* ((spec (mini-kernel:make-frozen-kernel-core-spec))
         (results (mini-kernel:check-kernel-spec-kl spec))
         (summary (mini-kernel:summarize-kernel-spec-results results)))
    (is-equal 6 (getf summary :total))
    (is-equal 4 (getf summary :accepted))
    (is-equal 2 (getf summary :rejected))
    (is-equal 6 (getf summary :matched))
    (is-equal 0 (getf summary :mismatched))))

(defun test-compare-frozen-kernel-spec-kr-kl ()
  (let* ((spec (mini-kernel:make-frozen-kernel-core-spec))
         (report (mini-kernel:compare-kernel-spec-kr-kl spec))
         (entries (getf report :entries)))
    (is-true (getf report :matchedp))
    (is-equal 6 (length entries))
    (is-true (every (lambda (entry) (getf entry :matchedp)) entries))
    (is-equal
     '((:wf-empty-context :accepted :accepted)
       (:typing-zero-nat :accepted :accepted)
       (:typing-zero-sort-rejected :rejected :rejected)
       (:defeq-zero-zero :accepted :accepted)
       (:defeq-zero-succ-zero-rejected :rejected :rejected)
       (:let-step-zero :accepted :accepted))
     (mapcar (lambda (entry)
               (list (getf entry :id)
                     (getf entry :kr-status)
                     (getf entry :kl-status)))
             entries))))

(defun test-certificate-kernel-spec-kr-kl ()
  (let* ((spec (mini-kernel:make-certificate-kernel-spec :accepted-limit 4 :rejected-limit 4))
         (kr-results (mini-kernel:check-kernel-spec-kr spec))
         (kl-results (mini-kernel:check-kernel-spec-kl spec))
         (kr-summary (mini-kernel:summarize-kernel-spec-results kr-results))
         (kl-summary (mini-kernel:summarize-kernel-spec-results kl-results))
         (report (mini-kernel:compare-kernel-spec-kr-kl spec)))
    (is-equal 8 (getf kr-summary :total))
    (is-equal 8 (getf kl-summary :total))
    (is-equal 4 (getf kr-summary :accepted))
    (is-equal 4 (getf kl-summary :accepted))
    (is-equal 4 (getf kr-summary :rejected))
    (is-equal 4 (getf kl-summary :rejected))
    (is-equal 8 (getf kr-summary :matched))
    (is-equal 8 (getf kl-summary :matched))
    (is-true (getf report :matchedp))
    (is-equal
     '((:proof-demo :accepted :accepted)
       (:zero-has-nat :accepted :accepted)
       (:ctx-var0-has-nat :accepted :accepted)
       (:let-zero-has-nat :accepted :accepted)
       (:zero-is-not-proof :rejected :rejected)
       (:wrong-equality-claim :rejected :rejected)
       (:ctx-var0-wrong-type :rejected :rejected)
       (:let-zero-not-proof :rejected :rejected))
     (mapcar (lambda (entry)
               (list (getf entry :id)
                     (getf entry :kr-status)
                     (getf entry :kl-status)))
             (getf report :entries)))))

(defun test-defeq-kernel-spec-kr-kl ()
  (let* ((spec (mini-kernel:make-defeq-kernel-spec))
         (kr-results (mini-kernel:check-kernel-spec-kr spec))
         (kl-results (mini-kernel:check-kernel-spec-kl spec))
         (kr-summary (mini-kernel:summarize-kernel-spec-results kr-results))
         (kl-summary (mini-kernel:summarize-kernel-spec-results kl-results))
         (report (mini-kernel:compare-kernel-spec-kr-kl spec)))
    (is-equal 5 (getf kr-summary :total))
    (is-equal 5 (getf kl-summary :total))
    (is-equal 4 (getf kr-summary :accepted))
    (is-equal 4 (getf kl-summary :accepted))
    (is-equal 1 (getf kr-summary :rejected))
    (is-equal 1 (getf kl-summary :rejected))
    (is-true (getf report :matchedp))
    (is-equal
     '((:defeq-add-zero-succ :accepted :accepted)
       (:defeq-zero-succ-zero :rejected :rejected)
       (:defeq-var0-var0 :accepted :accepted)
       (:defeq-beta-zero :accepted :accepted)
       (:defeq-let-zero :accepted :accepted))
     (mapcar (lambda (entry)
               (list (getf entry :id)
                     (getf entry :kr-status)
                     (getf entry :kl-status)))
             (getf report :entries)))))

(defun test-default-kernel-spec-suite ()
  (let ((suite (mini-kernel:make-default-kernel-spec-suite)))
    (is-equal 4 (length suite))
    (is-true
     (every (lambda (spec)
              (getf (mini-kernel:compare-kernel-spec-kr-kl spec) :matchedp))
            suite))))

(defun test-check-frozen-kernel-spec-defir ()
  (let* ((spec (mini-kernel:make-frozen-kernel-core-spec))
         (results (mini-kernel:check-kernel-spec-defir spec))
         (summary (mini-kernel:summarize-kernel-spec-results results)))
    (is-equal 6 (getf summary :total))
    (is-equal 4 (getf summary :accepted))
    (is-equal 2 (getf summary :rejected))
    (is-equal 6 (getf summary :matched))
    (is-equal 0 (getf summary :mismatched))))

(defun test-compare-frozen-kernel-spec-kr-kl-defir ()
  (let* ((spec (mini-kernel:make-frozen-kernel-core-spec))
         (report (mini-kernel:compare-kernel-spec-kr-kl-defir spec))
         (entries (getf report :entries)))
    (is-true (getf report :matchedp))
    (is-equal 6 (length entries))
    (is-true (every (lambda (entry) (getf entry :matchedp)) entries))
    (is-equal
     '((:wf-empty-context :accepted :accepted :accepted)
       (:typing-zero-nat :accepted :accepted :accepted)
       (:typing-zero-sort-rejected :rejected :rejected :rejected)
       (:defeq-zero-zero :accepted :accepted :accepted)
       (:defeq-zero-succ-zero-rejected :rejected :rejected :rejected)
       (:let-step-zero :accepted :accepted :accepted))
     (mapcar (lambda (entry)
               (list (getf entry :id)
                     (getf entry :kr-status)
                     (getf entry :kl-status)
                     (getf entry :defir-status)))
             entries))))

(defun test-default-kernel-spec-suite-kr-kl-defir ()
  (let ((suite (mini-kernel:make-default-kernel-spec-suite)))
    (is-equal 4 (length suite))
    (is-true
     (every (lambda (spec)
              (getf (mini-kernel:compare-kernel-spec-kr-kl-defir spec) :matchedp))
            suite))))

(defun test-step-kernel-spec-kr-kl-defir ()
  (let* ((spec (mini-kernel:make-step-kernel-spec))
         (report (mini-kernel:compare-kernel-spec-kr-kl-defir spec))
         (entries (getf report :entries)))
    (is-true (getf report :matchedp))
    (is-equal 5 (length entries))
    (is-equal
     '((:step-beta-zero :accepted :accepted :accepted)
       (:step-let-zero :accepted :accepted :accepted)
       (:step-nat-rec-zero :accepted :accepted :accepted)
       (:step-eq-rec-refl :accepted :accepted :accepted)
       (:step-zero-no-succ :rejected :rejected :rejected))
     (mapcar (lambda (entry)
               (list (getf entry :id)
                     (getf entry :kr-status)
                     (getf entry :kl-status)
                     (getf entry :defir-status)))
             entries))))

(defun run-tests ()
  (let* ((tests
           (list
            (cons "check-frozen-kernel-spec-kr"
                  #'test-check-frozen-kernel-spec-kr)
            (cons "check-frozen-kernel-spec-kl"
                  #'test-check-frozen-kernel-spec-kl)
            (cons "check-frozen-kernel-spec-defir"
                  #'test-check-frozen-kernel-spec-defir)
            (cons "compare-frozen-kernel-spec-kr-kl"
                  #'test-compare-frozen-kernel-spec-kr-kl)
            (cons "compare-frozen-kernel-spec-kr-kl-defir"
                  #'test-compare-frozen-kernel-spec-kr-kl-defir)
            (cons "certificate-kernel-spec-kr-kl"
                  #'test-certificate-kernel-spec-kr-kl)
            (cons "defeq-kernel-spec-kr-kl"
                  #'test-defeq-kernel-spec-kr-kl)
            (cons "step-kernel-spec-kr-kl-defir"
                  #'test-step-kernel-spec-kr-kl-defir)
            (cons "default-kernel-spec-suite"
                  #'test-default-kernel-spec-suite)
            (cons "default-kernel-spec-suite-kr-kl-defir"
                  #'test-default-kernel-spec-suite-kr-kl-defir)))
         (passed 0)
         (failed 0))
    (dolist (test tests)
      (if (run-test (car test) (cdr test))
          (incf passed)
          (incf failed)))
    (format t "~%passed: ~D failed: ~D~%" passed failed)
    (when (plusp failed)
      (fail-test "kernel spec test suite failed"))
    t))
