(let* ((source (or *load-truename* *compile-file-truename* (truename *default-pathname-defaults*)))
       (dir (make-pathname :name nil :type nil :defaults source)))
  (dolist (file '("package.lisp"
                  "spec-core.lisp"
                  "term-env.lisp"
                  "stage-ir.lisp"
                  "backend-protocol.lisp"
                  "advisory-artifacts.lisp"
                  "checked-proposals.lisp"
                  "json-lite.lisp"
                  "ast.lisp"
                  "normalize.lisp"
                  "eval.lisp"
                  "def-ir.lisp"
                  "smtlib.lisp"
                  "cnf.lisp"
                  "sat-core.lisp"
                  "bitblast.lisp"
                  "solver-stub.lisp"
                  "internal-audit.lisp"
                  "external-ingest.lisp"
                  "checker-implementation.lisp"
                  "subst.lisp"
                  "lean-def-ingest.lisp"
                  "scripted-alignment.lisp"
                  "frontend.lisp"
                  "reduce.lisp"
                  "typecheck.lisp"
                  "certificate.lisp"
                  "proof-ir.lisp"
                  "theorem-ir.lisp"
                  "theorem-proof.lisp"
                  "lean-schema.lisp"
                  "lean-ingest.lisp"
                  "reference-checker.lisp"
                  "certificate-corpus.lisp"
                  "bootstrap.lisp"
                  "demo.lisp"))
    (load (merge-pathnames file dir))))
