(in-package :mini-kernel)

(defun %canonicalize-commutative-terms (terms)
  (sort (copy-list terms) #'smt-term<))

(defun %smt-bv-mask (width)
  (1- (ash 1 width)))

(defun %ensure-same-bv-width (lhs rhs op)
  (let ((lw (smt-bv-width lhs))
        (rw (smt-bv-width rhs)))
    (unless (= lw rw)
      (kernel-error "~A requires equal bitvector widths, got ~S and ~S" op lw rw))
    lw))

(defun %int-linear-form-add-term (table name coefficient)
  (let ((current (gethash name table 0)))
    (setf (gethash name table) (+ current coefficient)))
  table)

(defun %int-linear-form-merge (target source scale)
  (maphash (lambda (name coefficient)
             (%int-linear-form-add-term target name (* scale coefficient)))
           source)
  target)

(defun %int-linear-form (term)
  (labels ((build (current)
             (case (smt-tag current)
               (:int-lit
                (values (make-hash-table :test #'equal) (smt-int-value current) t))
               (:var
                (if (equal (third current) (smt-int-sort))
                    (let ((table (make-hash-table :test #'equal)))
                      (%int-linear-form-add-term table (second current) 1)
                      (values table 0 t))
                    (values nil nil nil)))
               (:int-add
                (let ((table (make-hash-table :test #'equal))
                      (constant 0))
                  (dolist (part (rest current))
                    (multiple-value-bind (part-table part-constant ok)
                        (build part)
                      (unless ok
                        (return-from build (values nil nil nil)))
                      (%int-linear-form-merge table part-table 1)
                      (incf constant part-constant)))
                  (values table constant t)))
               (:int-sub
                (multiple-value-bind (lhs-table lhs-constant lhs-ok)
                    (build (second current))
                  (unless lhs-ok
                    (return-from build (values nil nil nil)))
                  (multiple-value-bind (rhs-table rhs-constant rhs-ok)
                      (build (third current))
                    (unless rhs-ok
                      (return-from build (values nil nil nil)))
                    (%int-linear-form-merge lhs-table rhs-table -1)
                    (values lhs-table (- lhs-constant rhs-constant) t))))
               (otherwise
                (values nil nil nil)))))
    (build term)))

(defun %int-linear-difference (lhs rhs)
  (multiple-value-bind (lhs-table lhs-constant lhs-ok)
      (%int-linear-form lhs)
    (unless lhs-ok
      (return-from %int-linear-difference (values nil nil nil)))
    (multiple-value-bind (rhs-table rhs-constant rhs-ok)
        (%int-linear-form rhs)
      (unless rhs-ok
        (return-from %int-linear-difference (values nil nil nil)))
      (%int-linear-form-merge lhs-table rhs-table -1)
      (values lhs-table (- lhs-constant rhs-constant) t))))

(defun %int-linear-zero-p (table)
  (let ((zero t))
    (maphash (lambda (_ coefficient)
               (declare (ignore _))
               (unless (zerop coefficient)
                 (setf zero nil)))
             table)
    zero))

(defun normalize-smt-term (term)
  (labels
      ((norm (current)
         (let ((tag (smt-tag current)))
           (case tag
             (:bool current)
             (:var current)
             (:int-lit current)
             (:bv-lit current)
             (:not
              (let ((inner (norm (second current))))
                (cond
                  ((smt-bool-true-p inner) (smt-bool-const nil))
                  ((smt-bool-false-p inner) (smt-bool-const t))
                  ((eq (smt-tag inner) :not) (second inner))
                  (t (smt-not inner)))))
             (:and
              (let* ((parts (mapcan (lambda (arg)
                                      (let ((normalized (norm arg)))
                                        (if (eq (smt-tag normalized) :and)
                                            (rest normalized)
                                            (list normalized))))
                                    (rest current)))
                     (filtered '()))
                (dolist (part parts)
                  (cond
                    ((smt-bool-false-p part)
                     (return-from norm (smt-bool-const nil)))
                    ((smt-bool-true-p part))
                    (t (push part filtered))))
                (setf filtered (%canonicalize-commutative-terms filtered))
                (cond
                  ((endp filtered) (smt-bool-const t))
                  ((endp (rest filtered)) (first filtered))
                  (t (cons :and filtered)))))
             (:or
              (let* ((parts (mapcan (lambda (arg)
                                      (let ((normalized (norm arg)))
                                        (if (eq (smt-tag normalized) :or)
                                            (rest normalized)
                                            (list normalized))))
                                    (rest current)))
                     (filtered '()))
                (dolist (part parts)
                  (cond
                    ((smt-bool-true-p part)
                     (return-from norm (smt-bool-const t)))
                    ((smt-bool-false-p part))
                    (t (push part filtered))))
                (setf filtered (%canonicalize-commutative-terms filtered))
                (cond
                  ((endp filtered) (smt-bool-const nil))
                  ((endp (rest filtered)) (first filtered))
                  (t (cons :or filtered)))))
             (:xor
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (cond
                  ((equal lhs rhs) (smt-bool-const nil))
                  ((smt-bool-false-p lhs) rhs)
                  ((smt-bool-false-p rhs) lhs)
                  ((smt-bool-true-p lhs) (norm (smt-not rhs)))
                  ((smt-bool-true-p rhs) (norm (smt-not lhs)))
                  (t (destructuring-bind (a b)
                         (%canonicalize-commutative-terms (list lhs rhs))
                       (smt-xor a b))))))
             (:=>
              (norm (smt-or (smt-not (second current)) (third current))))
             (:ite
              (let ((condition (norm (second current)))
                    (then-branch (norm (third current)))
                    (else-branch (norm (fourth current))))
                (cond
                  ((smt-bool-true-p condition) then-branch)
                  ((smt-bool-false-p condition) else-branch)
                  ((equal then-branch else-branch) then-branch)
                  (t (smt-ite condition then-branch else-branch)))))
             (:= 
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (cond
                  ((equal lhs rhs) (smt-bool-const t))
                  ((and (or (eq (smt-tag lhs) :int-lit)
                            (eq (smt-tag lhs) :var)
                            (eq (smt-tag lhs) :int-add)
                            (eq (smt-tag lhs) :int-sub))
                        (or (eq (smt-tag rhs) :int-lit)
                            (eq (smt-tag rhs) :var)
                            (eq (smt-tag rhs) :int-add)
                            (eq (smt-tag rhs) :int-sub)))
                   (multiple-value-bind (difference constant ok)
                       (%int-linear-difference lhs rhs)
                     (if (and ok (%int-linear-zero-p difference))
                         (smt-bool-const (zerop constant))
                         (smt-eq lhs rhs))))
                  ((and (eq (smt-tag lhs) :bv-lit) (eq (smt-tag rhs) :bv-lit))
                   (smt-bool-const (= (smt-bv-value lhs) (smt-bv-value rhs))))
                  ((or (and (smt-bool-true-p lhs) (smt-bool-false-p rhs))
                       (and (smt-bool-false-p lhs) (smt-bool-true-p rhs)))
                   (smt-bool-const nil))
                  (t (destructuring-bind (a b)
                         (%canonicalize-commutative-terms (list lhs rhs))
                       (smt-eq a b))))))
             (:bvnot
              (let ((inner (norm (second current))))
                (if (eq (smt-tag inner) :bv-lit)
                    (let* ((width (smt-bv-width inner))
                           (mask (%smt-bv-mask width)))
                      (smt-bv-lit width (logxor (smt-bv-value inner) mask)))
                    (smt-bvnot inner))))
             (:bvand
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (if (and (eq (smt-tag lhs) :bv-lit) (eq (smt-tag rhs) :bv-lit))
                    (let ((width (%ensure-same-bv-width lhs rhs :bvand)))
                      (smt-bv-lit width (logand (smt-bv-value lhs) (smt-bv-value rhs))))
                    (destructuring-bind (a b)
                        (%canonicalize-commutative-terms (list lhs rhs))
                      (smt-bvand a b)))))
             (:bvor
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (if (and (eq (smt-tag lhs) :bv-lit) (eq (smt-tag rhs) :bv-lit))
                    (let ((width (%ensure-same-bv-width lhs rhs :bvor)))
                      (smt-bv-lit width (logior (smt-bv-value lhs) (smt-bv-value rhs))))
                    (destructuring-bind (a b)
                        (%canonicalize-commutative-terms (list lhs rhs))
                      (smt-bvor a b)))))
             (:bvxor
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (if (and (eq (smt-tag lhs) :bv-lit) (eq (smt-tag rhs) :bv-lit))
                    (let ((width (%ensure-same-bv-width lhs rhs :bvxor)))
                      (smt-bv-lit width (logxor (smt-bv-value lhs) (smt-bv-value rhs))))
                    (destructuring-bind (a b)
                        (%canonicalize-commutative-terms (list lhs rhs))
                      (smt-bvxor a b)))))
             (:bvadd
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (if (and (eq (smt-tag lhs) :bv-lit) (eq (smt-tag rhs) :bv-lit))
                    (let* ((width (%ensure-same-bv-width lhs rhs :bvadd))
                           (modulus (ash 1 width)))
                      (smt-bv-lit width (mod (+ (smt-bv-value lhs) (smt-bv-value rhs))
                                             modulus)))
                    (smt-bvadd lhs rhs))))
             (:bvsub
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (if (and (eq (smt-tag lhs) :bv-lit) (eq (smt-tag rhs) :bv-lit))
                    (let* ((width (%ensure-same-bv-width lhs rhs :bvsub))
                           (modulus (ash 1 width)))
                      (smt-bv-lit width (mod (- (smt-bv-value lhs) (smt-bv-value rhs))
                                             modulus)))
                    (smt-bvsub lhs rhs))))
             (:concat
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (if (and (eq (smt-tag lhs) :bv-lit) (eq (smt-tag rhs) :bv-lit))
                    (let* ((lw (smt-bv-width lhs))
                           (rw (smt-bv-width rhs))
                           (value (logior (ash (smt-bv-value lhs) rw)
                                          (smt-bv-value rhs))))
                      (smt-bv-lit (+ lw rw) value))
                    (smt-concat lhs rhs))))
             (:extract
              (destructuring-bind (_ hi lo inner) current
                (declare (ignore _))
                (let ((normalized (norm inner)))
                  (when (< hi lo)
                    (kernel-error "extract requires hi >= lo, got ~S and ~S" hi lo))
                  (if (eq (smt-tag normalized) :bv-lit)
                      (let* ((width (1+ (- hi lo)))
                             (value (ldb (byte width lo) (smt-bv-value normalized))))
                        (smt-bv-lit width value))
                      (smt-extract hi lo normalized)))))
             (:ult
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (if (and (eq (smt-tag lhs) :bv-lit) (eq (smt-tag rhs) :bv-lit))
                    (progn
                      (%ensure-same-bv-width lhs rhs :ult)
                      (smt-bool-const (< (smt-bv-value lhs) (smt-bv-value rhs))))
                    (smt-ult lhs rhs))))
             (:int-add
              (let ((parts (mapcar #'norm (rest current))))
                (if (every (lambda (term) (eq (smt-tag term) :int-lit)) parts)
                    (smt-int-lit (reduce #'+ parts :key #'smt-int-value :initial-value 0))
                    (cons :int-add parts))))
             (:int-sub
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (if (and (eq (smt-tag lhs) :int-lit) (eq (smt-tag rhs) :int-lit))
                    (smt-int-lit (- (smt-int-value lhs) (smt-int-value rhs)))
                    (smt-int-sub lhs rhs))))
             (:int-mod
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (if (and (eq (smt-tag lhs) :int-lit) (eq (smt-tag rhs) :int-lit))
                    (smt-int-lit (mod (smt-int-value lhs) (smt-int-value rhs)))
                    (smt-int-mod lhs rhs))))
             (:int-lt
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (cond
                  ((and (eq (smt-tag lhs) :int-lit) (eq (smt-tag rhs) :int-lit))
                   (smt-bool-const (< (smt-int-value lhs) (smt-int-value rhs))))
                  (t
                   (multiple-value-bind (difference constant ok)
                       (%int-linear-difference lhs rhs)
                     (if (and ok (%int-linear-zero-p difference))
                         (smt-bool-const (< constant 0))
                         (smt-int-lt lhs rhs)))))))
             (:int-le
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (cond
                  ((and (eq (smt-tag lhs) :int-lit) (eq (smt-tag rhs) :int-lit))
                   (smt-bool-const (<= (smt-int-value lhs) (smt-int-value rhs))))
                  (t
                   (multiple-value-bind (difference constant ok)
                       (%int-linear-difference lhs rhs)
                     (if (and ok (%int-linear-zero-p difference))
                         (smt-bool-const (<= constant 0))
                         (smt-int-le lhs rhs)))))))
             (:int-gt
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (cond
                  ((and (eq (smt-tag lhs) :int-lit) (eq (smt-tag rhs) :int-lit))
                   (smt-bool-const (> (smt-int-value lhs) (smt-int-value rhs))))
                  (t
                   (multiple-value-bind (difference constant ok)
                       (%int-linear-difference lhs rhs)
                     (if (and ok (%int-linear-zero-p difference))
                         (smt-bool-const (> constant 0))
                         (smt-int-gt lhs rhs)))))))
             (:int-ge
              (let ((lhs (norm (second current)))
                    (rhs (norm (third current))))
                (cond
                  ((and (eq (smt-tag lhs) :int-lit) (eq (smt-tag rhs) :int-lit))
                   (smt-bool-const (>= (smt-int-value lhs) (smt-int-value rhs))))
                  (t
                   (multiple-value-bind (difference constant ok)
                       (%int-linear-difference lhs rhs)
                     (if (and ok (%int-linear-zero-p difference))
                         (smt-bool-const (>= constant 0))
                         (smt-int-ge lhs rhs)))))))
             (otherwise
              (kernel-error "unsupported SMT term for normalization: ~S" current))))))
    (norm term)))
