(defpackage :mini-kernel
  (:use :cl)
  (:shadow #:subst)
  (:export
   #:advisory-artifact
   #:advisory-artifact-backend-id
   #:advisory-artifact-kind
   #:advisory-artifact-payload
   #:advisory-artifact-metadata
   #:checked-proposal
   #:checked-proposal-backend-id
   #:checked-proposal-kind
   #:checked-proposal-payload
   #:checked-proposal-metadata
   #:certificate
   #:certificate-schema-version
   #:certificate-judgment-kind
   #:certificate-context
   #:certificate-term
   #:certificate-type
   #:certificate-env-digest
   #:certificate-config-digest
   #:certificate-checker-ids
   #:certificate-metadata
   #:make-typing-certificate
   #:validate-certificate
   #:check-certificate
   #:proof-claim
   #:proof-claim-kind
   #:proof-claim-context
   #:proof-claim-term
   #:proof-claim-type
   #:proof-claim-lhs
   #:proof-claim-rhs
   #:proof-claim-config-digest
   #:proof-claim-metadata
   #:proof-evidence
   #:proof-evidence-kind
   #:proof-evidence-payload
   #:proof-evidence-premises
   #:proof-evidence-checkedp
   #:proof-fragment
   #:proof-fragment-claim
   #:proof-fragment-evidence
   #:proof-fragment-checker-ids
   #:proof-fragment-config-digest
   #:proof-fragment-metadata
   #:make-has-type-claim
   #:make-defeq-claim
   #:make-step-claim
   #:make-wf-ctx-claim
   #:make-proof-evidence
   #:make-proof-fragment
   #:validate-proof-claim
   #:validate-proof-evidence
   #:validate-proof-fragment
   #:proof-claim->kernel-judgment
   #:proof-fragment->certificate
   #:check-proof-fragment
   #:j-d-proof-claim
   #:j-kr-proof-claim
   #:j-kl-proof-claim
   #:j-d-proof-fragment
   #:j-kr-proof-fragment
   #:j-kl-proof-fragment
   #:theorem-claim
   #:theorem-claim-obligation-id
   #:theorem-claim-parameters
   #:theorem-claim-config-digest
   #:theorem-claim-metadata
   #:theorem-evidence
   #:theorem-evidence-kind
   #:theorem-evidence-payload
   #:theorem-evidence-checkedp
   #:theorem-fragment
   #:theorem-fragment-claim
   #:theorem-fragment-evidence
   #:theorem-fragment-checker-ids
   #:theorem-fragment-config-digest
   #:theorem-fragment-metadata
   #:theorem-witness-bundle
   #:theorem-witness-bundle-obligation-id
   #:theorem-witness-bundle-parameters
   #:theorem-witness-bundle-checked
   #:theorem-witness-bundle-entries
   #:theorem-witness-bundle-failures
   #:theorem-witness-bundle-config-digest
   #:make-theorem-claim
   #:make-theorem-evidence
   #:make-theorem-fragment
   #:validate-theorem-claim
   #:validate-theorem-evidence
   #:validate-theorem-fragment
   #:validate-theorem-witness-bundle
   #:theorem-obligation-emitter
   #:theorem-obligation-verifier
   #:theorem-obligation-witness-builder
   #:make-jd-substitution-witness-bundle
   #:make-jd-weakening-witness-bundle
   #:make-jd-subject-reduction-witness-bundle
   #:make-jkr-soundness-witness-bundle
   #:make-jkr-fragment-completeness-witness-bundle
   #:make-jkl-jkr-equivalence-witness-bundle
   #:make-jdefir-jkr-equivalence-witness-bundle
   #:theorem-claim->witness-bundle
   #:verify-theorem-witness-bundle
   #:theorem-claim->fragment-certificate
   #:verify-theorem-fragment-certificate
   #:check-theorem-claim
   #:check-theorem-fragment
   #:theorem-statement
   #:theorem-statement-id
   #:theorem-statement-premises
   #:theorem-statement-conclusion
   #:theorem-statement-config-digest
   #:theorem-statement-metadata
   #:theorem-derivation
   #:theorem-derivation-kind
   #:theorem-derivation-payload
   #:theorem-derivation-subderivations
   #:theorem-derivation-metadata
   #:proof-claim->proposition
   #:theorem-claim->proposition
   #:validate-theorem-proposition
   #:make-theorem-statement
   #:make-premise-derivation
   #:make-proof-fragment-derivation
   #:make-theorem-fragment-derivation
   #:make-apply-theorem-fragment-derivation
   #:make-apply-relation-fragment-derivation
   #:make-and-intro-derivation
   #:make-and-elim-left-derivation
   #:make-and-elim-right-derivation
   #:validate-theorem-statement
   #:validate-theorem-derivation
   #:infer-theorem-derivation-proposition
   #:check-theorem-derivation
   #:lean-theorem-schema
   #:lean-theorem-schema-id
   #:lean-theorem-schema-module
   #:lean-theorem-schema-name
   #:lean-theorem-schema-source-kind
   #:lean-theorem-schema-obligation-id
   #:lean-theorem-schema-parameter-keys
   #:lean-theorem-schema-statement-builder
   #:*lean-theorem-schemas*
   #:valid-lean-theorem-source-kind-p
   #:validate-lean-theorem-schema
   #:find-lean-theorem-schema
   #:list-lean-theorem-schemas
   #:instantiate-lean-weakening-statement
   #:instantiate-lean-substitution-statement
   #:instantiate-lean-subject-reduction-statement
   #:instantiate-lean-krcheck-sound-statement
   #:instantiate-lean-theorem-statement
   #:lean-ingest-artifact
   #:lean-ingest-artifact-path
   #:lean-ingest-artifact-source-digest
   #:lean-ingest-artifact-schemas
   #:generate-lean-theorem-artifact
   #:validate-lean-ingest-artifact
   #:ingest-lean-theorem-artifact
   #:find-ingested-lean-theorem-schema
   #:list-ingested-lean-theorem-schemas
   #:instantiate-ingested-lean-theorem-statement
   #:check-ingested-lean-statement-parity
   #:run-scripted-alignment-pass
   #:print-scripted-alignment-summary
   #:lean-def-function
   #:lean-def-function-name
   #:lean-def-function-source-block
   #:lean-def-function-source-digest
   #:lean-def-function-evaluator
   #:lean-def-program
   #:lean-def-program-source-path
   #:lean-def-program-source-digest
   #:lean-def-program-functions
   #:*declarativecore-lean-def-source-path*
   #:validate-lean-def-program
   #:ingest-declarativecore-def-program
   #:*mini-kernel-whnf-lean-source-path*
   #:generate-lean-whnf-program
   #:ingest-mini-kernel-whnf-program
   #:find-ingested-lean-def-function
   #:list-ingested-lean-def-functions
   #:call-ingested-lean-def
   #:lower-ingested-lean-def-program-to-defir
   #:check-ingested-lean-def-parity
   #:defir-function
   #:defir-function-name
   #:defir-function-params
   #:defir-function-body
   #:defir-program
   #:defir-program-functions
   #:defir-program-metadata
   #:validate-defir-program
   #:find-defir-function
   #:call-defir-function
   #:make-mini-kernel-defir-program
   #:make-smt-core-defir-program
   #:make-smt-normalizer-defir-program
   #:merge-defir-programs
   #:certificate->corpus-entry
   #:normalize-stage-certificates
   #:make-advisory-store
   #:make-proposal-store
   #:emit-advisory-artifact
   #:emit-checked-proposal
   #:advisory-store-add
   #:advisory-store-find-by-kind
   #:advisory-store-find-by-backend
   #:proposal-store-add
   #:proposal-store-find-by-kind
   #:proposal-store-find-by-backend
   #:backend-id
   #:backend-result
   #:backend-result-backend-id
   #:backend-result-status
   #:backend-result-evidence
   #:backend-result-artifacts
   #:ingested-algorithm
   #:ingested-algorithm-name
   #:ingested-algorithm-lane
   #:ingested-algorithm-input-schema
   #:ingested-algorithm-output-schema
   #:ingested-algorithm-semantic-contract
   #:ingested-algorithm-reference-judgment
   #:ingested-algorithm-defir-program
   #:ingested-algorithm-config
   #:ingested-algorithm-agreement-theorem-kind
   #:ingested-algorithm-status
   #:ingested-algorithm-metadata
   #:backend-trust-class
   #:backend-reads
   #:backend-writes
   #:backend-proposes
   #:backend-layer
   #:backend-candidate-kind
   #:backend-spec-kind
   #:backend-evidence-kind
   #:backend-statuses
   #:valid-checker-status-p
   #:ensure-checker-status
   #:artifact-digest
   #:successor-state
   #:make-successor-state
   #:successor-state-next
   #:successor-state-label
   #:successor-state-metadata
   #:search-branch
   #:make-search-branch
   #:search-branch-state
   #:search-branch-history
   #:one-step-successors
   #:term-one-step-successors
   #:runtime-one-step-successors
   #:expand-frontier-once
   #:state-key
   #:branch-closes-p
   #:find-backend
   #:list-backends
   #:validate-ingested-algorithm
   #:register-ingested-algorithm
   #:find-ingested-algorithm
   #:list-ingested-algorithms
   #:ingested-algorithm-operations
   #:execute-ingested-algorithm
   #:compare-ingested-algorithm-operation
   #:clear-ingested-algorithm-registry
   #:make-bootstrap-env
   #:*kernel-spec*
   #:kernel-obligation
   #:kernel-obligation-id
   #:kernel-obligation-judgment
   #:kernel-obligation-expected-status
   #:kernel-obligation-semantic-tags
   #:kernel-obligation-source-ref
   #:kernel-obligation-metadata
   #:kernel-spec
   #:kernel-spec-id
   #:kernel-spec-obligations
   #:kernel-spec-semantic-tags
   #:kernel-spec-metadata
   #:kernel-judgment
   #:kernel-judgment-context
   #:kernel-judgment-term
   #:kernel-judgment-type
   #:kernel-judgment-config
   #:kernel-judgment-judgment-kind
   #:smt-judgment
   #:smt-judgment-formula
   #:smt-judgment-config
   #:smt-judgment-expected-status
   #:smt-obligation-class
   #:smt-obligation-class-id
   #:smt-obligation-class-polarity
   #:smt-obligation-class-statement
   #:smt-obligation-class-fragment-predicate
   #:smt-obligation-class-side-condition
   #:smt-obligation-class-projector
   #:kernel-core-algorithm
   #:kernel-core-algorithm-id
   #:kernel-core-algorithm-layer
   #:kernel-core-algorithm-status
   #:kernel-core-algorithm-theorem-target
   #:kernel-core-algorithm-callable
   #:kernel-core-algorithm-note
   #:bridge-law
   #:bridge-law-id
   #:bridge-law-obligation-class-id
   #:bridge-law-source-lane
   #:bridge-law-target-lane
   #:bridge-law-result-polarity
   #:bridge-law-side-predicate
   #:bridge-law-projector
   #:bridge-law-statement
   #:bridge-law-theorem-target
   #:smt-core-algorithm
   #:smt-core-algorithm-id
   #:smt-core-algorithm-layer
   #:smt-core-algorithm-status
   #:smt-core-algorithm-theorem-target
   #:smt-core-algorithm-callable
   #:smt-core-algorithm-note
   #:admitted-obligation-class
   #:admitted-obligation-class-id
   #:admitted-obligation-class-source-lane
   #:admitted-obligation-class-target-lane
   #:admitted-obligation-class-smt-obligation-class-id
   #:admitted-obligation-class-result-polarity
   #:admitted-obligation-class-fragment-predicate
   #:admitted-obligation-class-side-predicate
   #:admitted-obligation-class-projector
   #:admitted-obligation-class-statement
   #:admitted-obligation-class-theorem-target
   #:theorem-bridge-binding
   #:theorem-bridge-binding-theorem-obligation-id
   #:theorem-bridge-binding-admitted-obligation-id
   #:theorem-bridge-binding-result-polarity
   #:theorem-bridge-binding-note
   #:theorem-obligation
   #:theorem-obligation-id
   #:theorem-obligation-lane
   #:theorem-obligation-relation
   #:theorem-obligation-statement
   #:theorem-obligation-witness-kind
   #:theorem-counterexample
   #:theorem-counterexample-obligation-id
   #:theorem-counterexample-lane
   #:theorem-counterexample-relation
   #:theorem-counterexample-payload
   #:theorem-witness
   #:theorem-witness-obligation-id
   #:theorem-witness-lane
   #:theorem-witness-relation
   #:theorem-witness-checked
   #:theorem-witness-payload
   #:theorem-fragment-certificate
   #:theorem-fragment-certificate-obligation-id
   #:theorem-fragment-certificate-parameters
   #:theorem-fragment-certificate-checked
   #:theorem-fragment-certificate-payload-digest
   #:theorem-fragment-certificate-status
   #:theorem-fragment-certificate-config-digest
   #:closure-backlog-entry
   #:closure-backlog-entry-id
   #:closure-backlog-entry-lane
   #:closure-backlog-entry-current-status
   #:closure-backlog-entry-target-relation
   #:closure-backlog-entry-required-theorem
   #:closure-backlog-entry-dependencies
   #:closure-backlog-entry-blocking-dependency
   #:closure-backlog-entry-notes
   #:*metakernel-obligations*
   #:*closure-backlog*
   #:find-theorem-obligation
   #:find-closure-backlog-entry
   #:closure-backlog-summary
   #:executable-closure-backlog
   #:runtime-callable-row
   #:runtime-callable-row-operation-id
   #:runtime-callable-row-name
   #:runtime-callable-row-callable
   #:runtime-callable-row-kind
   #:runtime-callable-row-lane
   #:runtime-callable-row-ref-id
   #:runtime-callable-row-note
   #:runtime-capability-class
   #:runtime-capability-class-id
   #:runtime-capability-class-lane
   #:runtime-capability-class-authority-kind
   #:runtime-capability-class-callable-rows
   #:runtime-capability-class-semantic-contract
   #:runtime-capability-class-meta
   #:formal-constraint-class
   #:formal-constraint-class-id
   #:formal-constraint-class-lane
   #:formal-constraint-class-kind
   #:formal-constraint-class-callable
   #:formal-constraint-class-expected-result-kind
   #:formal-constraint-class-note
   #:formal-admission-policy
   #:formal-admission-policy-id
   #:formal-admission-policy-allowed-invocations
   #:formal-admission-policy-required-evidence
   #:formal-admission-policy-trusted-boundaries
   #:formal-admission-policy-forbidden-mutations
   #:formal-admission-policy-note
   #:formal-capability-class
   #:formal-capability-class-id
   #:formal-capability-class-callable-rows
   #:formal-capability-class-operations
   #:formal-capability-class-constraint-classes
   #:formal-capability-class-evidence-kinds
   #:formal-capability-class-trusted-boundaries
   #:formal-capability-class-admission-policy
   #:formal-capability-class-meta
   #:formal-capability-report
   #:formal-capability-report-capability-id
   #:formal-capability-report-callable-count
   #:formal-capability-report-operation-count
   #:formal-capability-report-constraint-count
   #:formal-capability-report-evidence-kinds
   #:formal-capability-report-trusted-boundaries
   #:formal-capability-report-admission-policy-id
   #:formal-capability-report-summary
   #:formal-capability-invocation
   #:formal-capability-invocation-operation-id
   #:formal-capability-invocation-args
   #:formal-capability-invocation-kwargs
   #:formal-capability-operation
   #:formal-capability-operation-id
   #:formal-capability-operation-callable-row
   #:formal-capability-operation-constraint-classes
   #:formal-capability-operation-trusted-boundaries
   #:formal-capability-operation-required-evidence
   #:formal-capability-operation-admissible-caller-classes
   #:formal-capability-plan
   #:formal-capability-plan-operation-id
   #:formal-capability-plan-admissible-p
   #:formal-capability-plan-reason
   #:formal-capability-plan-operation
   #:formal-capability-plan-mutation-kind
   #:formal-capability-plan-diagnostics
   #:formal-capability-result
   #:formal-capability-result-operation-id
   #:formal-capability-result-status
   #:formal-capability-result-evidence-kind
   #:formal-capability-result-payload
   #:formal-capability-result-trusted-boundaries
   #:formal-capability-result-rejection-reason
   #:formal-capability-result-diagnostics
   #:search-kernel-obligation-kind
   #:search-kernel-obligation-kind-id
   #:search-kernel-obligation-kind-severity
   #:search-kernel-obligation-kind-projection-operation
   #:search-kernel-obligation-kind-payload-schema
   #:search-kernel-obligation-kind-freshness-law
   #:search-kernel-obligation-kind-note
   #:search-formal-obligation
   #:search-formal-obligation-id
   #:search-formal-obligation-kind
   #:search-formal-obligation-severity
   #:search-formal-obligation-scope
   #:search-formal-obligation-projection-seed
   #:search-formal-obligation-freshness-law
   #:search-formal-obligation-source-operation
   #:search-formal-obligation-status
   #:search-formal-obligation-metadata
   #:search-obligation-projection
   #:search-obligation-projection-obligation-id
   #:search-obligation-projection-kind
   #:search-obligation-projection-operation-id
   #:search-obligation-projection-payloads
   #:search-obligation-projection-totality-class
   #:search-obligation-projection-metadata
   #:search-formal-evidence
   #:search-formal-evidence-id
   #:search-formal-evidence-obligation-id
   #:search-formal-evidence-obligation-kind
   #:search-formal-evidence-evidence-kind
   #:search-formal-evidence-judgment
   #:search-formal-evidence-status
   #:search-formal-evidence-certificate
   #:search-formal-evidence-scope
   #:search-formal-evidence-freshness-status
   #:search-formal-evidence-resource-row
   #:search-formal-evidence-metadata
   #:search-evidence-status
   #:search-evidence-status-id
   #:search-evidence-status-terminalp
   #:search-evidence-status-freshness-class
   #:search-evidence-status-polarity
   #:search-evidence-status-note
   #:search-evidence-state
   #:make-search-evidence-state
   #:search-evidence-state-state-id
   #:search-evidence-state-obligation-statuses
   #:search-evidence-state-live-evidence-ids
   #:search-evidence-state-supersession-links
   #:search-evidence-state-hard-debt
   #:search-evidence-state-advisory-debt
   #:search-evidence-state-coverage-summary
   #:search-evidence-state-freshness-summary
   #:search-evidence-state-status
   #:search-evidence-state-metadata
   #:search-evidence-monotonicity-result
   #:make-search-evidence-monotonicity-result
   #:search-evidence-monotonicity-result-state-id
   #:search-evidence-monotonicity-result-status
   #:search-evidence-monotonicity-result-preserved-evidence-ids
   #:search-evidence-monotonicity-result-appended-evidence-ids
   #:search-evidence-monotonicity-result-supersession-links
   #:search-evidence-monotonicity-result-diagnostics
   #:search-evidence-frontier
   #:make-search-evidence-frontier
   #:search-evidence-frontier-state-id
   #:search-evidence-frontier-live-frontier
   #:search-evidence-frontier-superseded-evidence-ids
   #:search-evidence-frontier-diagnostics
   #:search-evidence-update
   #:search-evidence-update-state-id
   #:search-evidence-update-evidence-ids
   #:search-evidence-update-obligation-statuses
   #:search-evidence-update-live-evidence-ids
   #:search-evidence-update-supersession-links
   #:search-evidence-update-hard-debt
   #:search-evidence-update-advisory-debt
   #:search-evidence-update-coverage-summary
   #:search-evidence-update-freshness-summary
   #:search-evidence-update-status
   #:search-evidence-update-metadata
   #:search-admission-law
   #:search-admission-law-id
   #:search-admission-law-hard-obligation-kinds
   #:search-admission-law-advisory-obligation-kinds
   #:search-admission-law-stale-threshold
   #:search-admission-law-reject-on-fail-p
   #:search-admission-law-kernel-requirements
   #:search-admission-law-note
   #:search-admission-result
   #:search-admission-result-law-id
   #:search-admission-result-state-id
   #:search-admission-result-status
   #:search-admission-result-hard-debt
   #:search-admission-result-advisory-debt
   #:search-admission-result-failing-obligation-kinds
   #:search-admission-result-diagnostics
   #:search-supersession-consistency-result
   #:make-search-supersession-consistency-result
   #:search-supersession-consistency-result-state-id
   #:search-supersession-consistency-result-status
   #:search-supersession-consistency-result-covered-obligation-ids
   #:search-supersession-consistency-result-uncovered-obligation-ids
   #:search-supersession-consistency-result-diagnostics
   #:search-legality-clause
   #:search-legality-clause-id
   #:search-legality-clause-severity
   #:search-legality-clause-note
   #:search-operator-class
   #:search-operator-class-id
   #:search-operator-class-subject-kinds
   #:search-operator-class-mandatory-obligation-kinds
   #:search-operator-class-kernel-requirements
   #:search-operator-class-replay-required-p
   #:search-operator-class-note
   #:search-operator-instance
   #:search-operator-instance-id
   #:search-operator-instance-operator-class-id
   #:search-operator-instance-target-zone
   #:search-operator-instance-source-operation
   #:search-operator-instance-replay-token
   #:search-operator-instance-budget-row
   #:search-operator-instance-metadata
   #:search-bridge-totality-result
   #:search-bridge-totality-result-obligation-id
   #:search-bridge-totality-result-obligation-kind
   #:search-bridge-totality-result-status
   #:search-bridge-totality-result-projection-operation
   #:search-bridge-totality-result-payload-count
   #:search-bridge-totality-result-route-operation-id
   #:search-bridge-totality-result-diagnostics
   #:search-legal-transition
   #:search-legal-transition-operator-instance-id
   #:search-legal-transition-operator-class-id
   #:search-legal-transition-state-id
   #:search-legal-transition-status
   #:search-legal-transition-satisfied-clauses
   #:search-legal-transition-failing-clauses
   #:search-legal-transition-bridge-totality-results
   #:search-legal-transition-diagnostics
   #:compiler-family
   #:compiler-family-id
   #:compiler-family-package-name
   #:compiler-family-source-path
   #:compiler-family-dependency-paths
   #:compiler-family-entrypoints
   #:compiler-family-artifact-kinds
   #:compiler-family-note
   #:compiler-family-metadata
   #:compiler-obligation-kind
   #:compiler-obligation-kind-id
   #:compiler-obligation-kind-severity
   #:compiler-obligation-kind-check-operation
   #:compiler-obligation-kind-required-artifacts
   #:compiler-obligation-kind-note
   #:compiler-check-result
   #:compiler-check-result-family-id
   #:compiler-check-result-obligation-kind
   #:compiler-check-result-source-id
   #:compiler-check-result-control-id
   #:compiler-check-result-status
   #:compiler-check-result-diagnostics
   #:compiler-check-result-metadata
   #:runtime-constitution
   #:runtime-constitution-id
   #:runtime-constitution-authority-ref
   #:runtime-constitution-machine-ref
   #:runtime-constitution-registry-digest
   #:runtime-constitution-manifests
   #:runtime-constitution-authority-state
   #:runtime-constitution-live-state
   #:runtime-constitution-rehydration-state
   #:runtime-constitution-synchronization-state
   #:runtime-constitution-capability-classes
   #:runtime-constitution-kernel-core-algorithms
   #:runtime-constitution-smt-core-algorithms
   #:runtime-constitution-admitted-obligations
   #:runtime-constitution-theorem-bindings
   #:runtime-constitution-closure-backlog
   #:runtime-constitution-meta
   #:*runtime-constitution-registry*
   #:runtime-constitution-id-for-state
   #:make-formal-runtime-capability-class
   #:record-runtime-constitution
   #:find-runtime-constitution
   #:list-runtime-constitutions
   #:reset-runtime-constitution-registry
   #:make-runtime-constitution-manifests
   #:runtime-capability-class-json-object
   #:formal-constraint-class-json-object
   #:formal-admission-policy-json-object
   #:formal-capability-class-json-object
   #:formal-capability-manifest-object
   #:runtime-constitution-callable-rows
   #:find-runtime-callable-row
   #:runtime-callable-row-argument-keys
   #:find-formal-capability-operation
   #:formal-capability-operations-for-constraint-class
   #:runtime-constitution-json-object
   #:runtime-constitution-witness-object
   #:make-formal-constraint-classes
   #:build-formal-admission-policy
   #:make-formal-capability-class-object
   #:current-formal-capability-class
   #:evaluate-formal-capability-report
   #:evaluate-formal-synthesis-scenario
   #:check-formal-capability-consistency
   #:compiler-family-object
   #:list-compiler-families
   #:describe-compiler-family
   #:find-compiler-family
   #:compiler-obligation-kind-object
   #:list-compiler-obligation-kinds
   #:find-compiler-obligation-kind
   #:check-compiler-schema
   #:check-compiler-control-determinism
   #:check-compiler-lowering-totality
   #:check-compiler-installed-generation
   #:check-compiler-layout
   #:check-compiler-roundtrip
   #:check-compiler-image-closure
   #:check-compiler-trace-parity
   #:search-kernel-obligation-kind-object
   #:list-search-kernel-obligation-kinds
   #:find-search-kernel-obligation-kind
   #:search-evidence-status-object
   #:list-search-evidence-statuses
   #:find-search-evidence-status
   #:build-search-evidence-state-from-update
   #:evaluate-search-evidence-frontier
   #:search-legality-clause-object
   #:list-search-legality-clauses
   #:find-search-legality-clause
   #:search-operator-class-object
   #:list-search-operator-classes
   #:find-search-operator-class
   #:search-admission-law-object
   #:list-search-admission-laws
   #:find-search-admission-law
   #:build-search-operator-instance
   #:build-search-formal-obligation
   #:project-search-formal-obligation
   #:evaluate-search-bridge-totality
   #:build-search-formal-evidence
   #:apply-search-evidence-update
   #:evaluate-search-evidence-monotonicity
   #:evaluate-search-supersession-consistency
   #:evaluate-search-legal-transition
   #:evaluate-search-admission-law
   #:plan-formal-capability-invocation
   #:check-formal-capability-invocation
   #:invoke-formal-capability
   #:invoke-formal-constraint-class
   #:rehydrate-current-runtime-constitution
   #:current-runtime-constitution
   #:lsip-stratum
   #:lsip-stratum-id
   #:lsip-stratum-band
   #:lsip-stratum-meaning
   #:lsip-stratum-current-carrier
   #:lsip-stratum-main-implementation
   #:lsip-stratum-explicit-status
   #:lsip-stratum-shared-lane-status
   #:lsip-stratum-rust-legacy-status
   #:lsip-stratum-afsm-lane-status
   #:lsip-stratum-note
   #:lsip-lowering-edge
   #:lsip-lowering-edge-id
   #:lsip-lowering-edge-source-strata
   #:lsip-lowering-edge-target-strata
   #:lsip-lowering-edge-lowering-family
   #:lsip-lowering-edge-invariant-families
   #:lsip-lowering-edge-future-gate-kind
   #:lsip-lowering-edge-status
   #:lsip-lowering-edge-note
   #:lsip-edge-contract
   #:lsip-edge-contract-id
   #:lsip-edge-contract-edge-id
   #:lsip-edge-contract-contract-family
   #:lsip-edge-contract-obligation-classes
   #:lsip-edge-contract-candidate-constraint-classes
   #:lsip-edge-contract-required-evidence
   #:lsip-edge-contract-blocking-gaps
   #:lsip-edge-contract-note
   #:lsip-stratum-object
   #:lsip-stratum-object-id
   #:lsip-stratum-object-stratum-id
   #:lsip-stratum-object-object-id
   #:lsip-stratum-object-summary
   #:lsip-stratum-object-payload
   #:lsip-stratum-object-digest
   #:lsip-stratum-object-metadata
   #:lsip-relation
   #:lsip-relation-id
   #:lsip-relation-edge-id
   #:lsip-relation-source-objects
   #:lsip-relation-target-objects
   #:lsip-relation-facts
   #:lsip-relation-metadata
   #:lsip-law
   #:lsip-law-id
   #:lsip-law-edge-id
   #:lsip-law-obligation-class
   #:lsip-law-relation-kind
   #:lsip-law-required-facts
   #:lsip-law-predicate
   #:lsip-law-evidence-kind
   #:lsip-law-note
   #:lsip-law-result
   #:lsip-law-result-law-id
   #:lsip-law-result-edge-id
   #:lsip-law-result-relation-id
   #:lsip-law-result-status
   #:lsip-law-result-evidence-kind
   #:lsip-law-result-payload
   #:lsip-law-result-diagnostics
   #:lsip-edge-gate
   #:lsip-edge-gate-edge-id
   #:lsip-edge-gate-contract-id
   #:lsip-edge-gate-operation-id
   #:lsip-edge-gate-supported-law-ids
   #:lsip-edge-gate-supported-obligation-classes
   #:lsip-edge-gate-missing-obligation-classes
   #:lsip-edge-gate-available-constraint-classes
   #:lsip-edge-gate-coverage-status
   #:lsip-edge-gate-note
   #:lsip-edge-gate-result
   #:lsip-edge-gate-result-edge-id
   #:lsip-edge-gate-result-contract-id
   #:lsip-edge-gate-result-status
   #:lsip-edge-gate-result-law-results
   #:lsip-edge-gate-result-missing-obligation-classes
   #:lsip-edge-gate-result-diagnostics
   #:lsip-edge-capability-surface
   #:lsip-edge-capability-surface-edge-id
   #:lsip-edge-capability-surface-contract-id
   #:lsip-edge-capability-surface-candidate-constraint-classes
   #:lsip-edge-capability-surface-available-constraint-classes
   #:lsip-edge-capability-surface-missing-constraint-classes
   #:lsip-edge-capability-surface-supported-law-ids
   #:lsip-edge-capability-surface-missing-obligation-classes
   #:lsip-edge-capability-surface-coverage-status
   #:lsip-edge-capability-surface-note
   #:lsip-edge-search-alignment
   #:lsip-edge-search-alignment-edge-id
   #:lsip-edge-search-alignment-contract-id
   #:lsip-edge-search-alignment-family
   #:lsip-edge-search-alignment-search-ir-id
   #:lsip-edge-search-alignment-projection-lane
   #:lsip-edge-search-alignment-candidate-constraint-classes
   #:lsip-edge-search-alignment-matched-constraint-classes
   #:lsip-edge-search-alignment-required-obligation-classes
   #:lsip-edge-search-alignment-supported-obligation-classes
   #:lsip-edge-search-alignment-missing-obligation-classes
   #:lsip-edge-search-alignment-coverage-status
   #:lsip-edge-search-alignment-note
   #:lsip-search-preparation-manifest
   #:lsip-search-preparation-manifest-edge-count
   #:lsip-search-preparation-manifest-alignment-count
   #:lsip-search-preparation-manifest-ready-edge-count
   #:lsip-search-preparation-manifest-partial-edge-count
   #:lsip-search-preparation-manifest-edge-search-alignments
   #:lsip-search-preparation-manifest-summary
   #:lsip-formal-preparation-report
   #:lsip-formal-preparation-report-stratum-count
   #:lsip-formal-preparation-report-edge-count
   #:lsip-formal-preparation-report-contract-count
   #:lsip-formal-preparation-report-capability-surface-count
   #:lsip-formal-preparation-report-blocking-gaps
   #:lsip-formal-preparation-report-edge-summaries
   #:lsip-formal-preparation-report-summary
   #:*lsip-strata*
   #:*lsip-lowering-edges*
   #:*lsip-edge-contracts*
   #:find-lsip-stratum
   #:list-lsip-strata
   #:find-lsip-lowering-edge
   #:list-lsip-lowering-edges
   #:find-lsip-edge-contract
   #:list-lsip-edge-contracts
   #:find-lsip-edge-contract-for-edge
   #:find-lsip-law
   #:list-lsip-laws
   #:list-lsip-laws-for-edge
   #:compile-lsip-stratum-object
   #:compile-lsip-relation
   #:check-lsip-law
   #:build-lsip-edge-gate
   #:list-lsip-edge-gates
   #:check-lsip-edge-gate
   #:build-lsip-edge-capability-surface
   #:list-lsip-edge-capability-surfaces
   #:build-lsip-edge-search-alignment
   #:list-lsip-edge-search-alignments
   #:evaluate-lsip-search-preparation-manifest
   #:evaluate-lsip-formal-preparation-report
   #:make-typing-judgment
   #:make-defeq-judgment
   #:make-step-judgment
   #:make-wf-context-judgment
   #:make-smt-status-judgment
   #:check-kernel-obligation-kr
   #:check-kernel-obligation-kl
   #:check-kernel-obligation-defir
   #:check-kernel-spec-kr
   #:check-kernel-spec-kl
   #:check-kernel-spec-defir
   #:summarize-kernel-spec-results
   #:compare-kernel-obligation-kr-kl
   #:compare-kernel-spec-kr-kl
   #:compare-kernel-obligation-kr-kl-defir
   #:compare-kernel-spec-kr-kl-defir
   #:certificate->kernel-obligation
   #:make-certificate-kernel-spec
   #:make-defeq-kernel-spec
   #:make-step-kernel-spec
   #:make-frozen-kernel-core-spec
   #:make-default-kernel-spec-suite
   #:j-d
   #:j-kr
   #:j-kl
   #:j-smt
   #:*kernel-core-algorithms*
   #:find-kernel-core-algorithm
   #:list-kernel-core-algorithms
   #:*smt-core-algorithms*
   #:find-smt-core-algorithm
   #:list-smt-core-algorithms
   #:*smt-obligation-classes*
   #:find-smt-obligation-class
   #:*admitted-obligation-classes*
   #:find-admitted-obligation-class
   #:list-admitted-obligation-classes
   #:*theorem-bridge-bindings*
   #:find-theorem-bridge-binding
   #:list-theorem-bridge-bindings
   #:*bridge-laws*
   #:find-bridge-law
   #:list-bridge-laws
   #:normalization-side-condition
   #:boolean-unsat-side-condition
   #:bitvector-unsat-side-condition
   #:int-unsat-side-condition
   #:affine-int-contradiction-side-condition
   #:project-normalization-obligation
   #:project-smt-obligation
   #:project-admitted-obligation
   #:smt-obligation-side-condition
   #:admitted-obligation-side-condition
   #:j-smt-obligation-bridge
   #:j-smt-admitted-obligation-bridge
   #:j-smt-normalization-bridge
   #:summarize-kernel-spec-audit-entries
   #:run-kernel-spec-kr-kl-audit
   #:run-kernel-spec-kr-kl-defir-audit
   #:stage
   #:stage-manifest
   #:stage-manifest-stage-id
   #:stage-manifest-env-digest
   #:stage-manifest-config-digest
   #:stage-manifest-certificate-ids
   #:stage-manifest-provenance
   #:stage-verification-bundle
   #:stage-verification-bundle-stage-id
   #:stage-verification-bundle-env-digest
   #:stage-verification-bundle-config-digest
   #:stage-verification-bundle-agreement
   #:stage-verification-bundle-bounded
   #:stage-verification-bundle-external
   #:stage-verification-bundle-protocol
   #:smt-obligation-bundle
   #:smt-obligation-bundle-obligation-id
   #:smt-obligation-bundle-logic
   #:smt-obligation-bundle-input
   #:smt-obligation-bundle-input-digest
   #:smt-obligation-bundle-normalized-digest
   #:smt-obligation-bundle-normalized-term
   #:smt-obligation-bundle-assumption-ids
   #:smt-obligation-bundle-unsat-core
   #:smt-obligation-bundle-status
   #:smt-obligation-bundle-evidence-kind
   #:smt-obligation-bundle-solver-lane
   #:smt-obligation-bundle-trace-ref
   #:smt-cnf-bundle
   #:smt-cnf-bundle-obligation-id
   #:smt-cnf-bundle-logic
   #:smt-cnf-bundle-input-digest
   #:smt-cnf-bundle-normalized-digest
   #:smt-cnf-bundle-cnf-digest
   #:smt-cnf-bundle-var-count
   #:smt-cnf-bundle-clause-count
   #:smt-cnf-bundle-root-literal
   #:smt-cnf-bundle-assumption-ids
   #:smt-cnf-bundle-unsat-core
   #:smt-cnf-bundle-status
   #:smt-cnf-bundle-solver-lane
   #:smt-cnf-bundle-trace-ref
   #:protocol-check-bundle
   #:protocol-check-bundle-protocol-id
   #:protocol-check-bundle-query
   #:protocol-check-bundle-query-digest
   #:protocol-check-bundle-result-digest
   #:protocol-check-bundle-status
   #:protocol-check-bundle-evidence-kind
   #:protocol-check-bundle-checker-lane
   #:protocol-check-bundle-trace-ref
   #:make-protocol-check-bundle
   #:external-report-bundle
   #:external-report-bundle-artifact-id
   #:external-report-bundle-source-path
   #:external-report-bundle-source-digest
   #:external-report-bundle-report-kind
   #:external-report-bundle-summary
   #:external-report-bundle-summary-digest
   #:external-report-bundle-status
   #:external-report-bundle-trace-ref
   #:make-external-report-bundle
   #:serialize-backend-result
   #:deserialize-backend-result
   #:serialize-stage-verification-bundle
   #:deserialize-stage-verification-bundle
   #:emit-stage-verification-bundle
   #:activate-stage-from-proposal
   #:stage-id
   #:stage-env
   #:stage-reference-env
   #:stage-advisory-store
   #:stage-certificates
   #:stage-external-bundles
   #:stage-config-digest
   #:stage-env-digest
   #:stage-activatedp
   #:make-stage-manifest
   #:make-stage
   #:make-stage-from-surface-specs
   #:make-stage-verification-bundle
   #:check-stage-manifest
   #:check-stage-certificates
   #:run-model-check
   #:verify-stage
   #:verify-stage-from-surface-specs
   #:emit-verified-stage-proposal
   #:activate-stage-from-bundle
   #:check-stage-corpus-agreement
   #:check-stage-bounded-obligations
   #:check-stage-activation-protocol
   #:activate-stage-if-verified
   #:lower-term
   #:compile-stage-surface-certificates
   #:smt-bool-sort
   #:smt-int-sort
   #:smt-bv-sort
   #:smt-array-sort
   #:smt-bool-const
   #:smt-var
   #:smt-int-lit
   #:smt-bv-lit
   #:smt-not
   #:smt-and
   #:smt-or
   #:smt-xor
   #:smt-implies
   #:smt-ite
   #:smt-eq
   #:smt-bvnot
   #:smt-bvand
   #:smt-bvor
   #:smt-bvxor
   #:smt-bvadd
   #:smt-bvsub
   #:smt-int-add
   #:smt-int-sub
   #:smt-int-mod
   #:smt-int-lt
   #:smt-int-le
   #:smt-int-gt
   #:smt-int-ge
   #:smt-concat
   #:smt-extract
   #:smt-ult
   #:normalize-smt-term
   #:eval-smt-term
   #:core-closedn-p
   #:enumerate-bounded-core-terms
   #:bounded-smt-audit-formulas
   #:run-shift-closure-audit
   #:run-subst-irrelevance-audit
   #:run-smt-normalization-audit
   #:emit-jd-substitution-fragment-certificate
   #:verify-jd-substitution-fragment-certificate
   #:emit-jd-weakening-fragment-certificate
   #:verify-jd-weakening-fragment-certificate
   #:emit-jd-subject-reduction-fragment-certificate
   #:verify-jd-subject-reduction-fragment-certificate
   #:emit-jd-jkr-soundness-fragment-certificate
   #:verify-jd-jkr-soundness-fragment-certificate
   #:emit-jd-jkr-completeness-fragment-certificate
   #:verify-jd-jkr-fragment-completeness-fragment-certificate
   #:emit-jkr-jkl-equivalence-fragment-certificate
   #:verify-jkr-jkl-equivalence-fragment-certificate
   #:emit-jkr-defir-equivalence-fragment-certificate
   #:verify-jkr-defir-equivalence-fragment-certificate
   #:run-jd-substitution-audit
   #:run-jd-weakening-audit
   #:run-jd-subject-reduction-audit
   #:run-jd-jkr-equivalence-audit
   #:run-jd-jkr-completeness-audit
   #:run-jkr-jkl-equivalence-audit
   #:run-jkr-defir-equivalence-obligation-audit
   #:run-smt-normalization-bridge-audit
   #:run-smt-boolean-unsat-bridge-audit
   #:run-smt-bitvector-unsat-bridge-audit
   #:run-smt-int-unsat-bridge-audit
   #:run-smt-affine-int-contradiction-bridge-audit
   #:run-smt-obligation-catalog-audit
   #:run-stage1-jr-jl-equivalence-audit
   #:run-stage1-jr-soundness-audit
   #:*theorem-audit-runners*
   #:*metakernel-closure-profiles*
   #:find-theorem-audit-runner
   #:find-metakernel-closure-profile
   #:run-theorem-obligation-audit
   #:evaluate-metakernel-closure
   #:summarize-metakernel-closure-results
   #:evaluate-metakernel-closure-profile
   #:run-kr-kl-disagreement-audit
   #:run-kr-defir-disagreement-audit
   #:run-jkr-defir-equivalence-audit
   #:run-whnf-agreement-audit
   #:json-object-get
   #:read-json-file
   #:ingest-lsip-closure-report
   #:ingest-mir-report
   #:smtlib-sort->sort
   #:smtlib-term->ast
   #:read-smtlib-forms
   #:run-smtlib-commands
   #:run-smtlib-file
   #:summarize-smtlib-results
   #:summarize-smtlib-file
   #:sweep-smtlib-directory
   #:smt-obligation
   #:make-smt-obligation
   #:smt-obligation-id
   #:smt-obligation-label
   #:smt-obligation-logic
   #:smt-obligation-vars
   #:smt-obligation-assumptions
   #:smt-obligation-goal
   #:smt-obligation-polarity
   #:smt-obligation-expected-status
   #:smt-obligation-unknown-policy
   #:smt-obligation-semantic-tags
   #:smt-obligation-source-ref
   #:smt-obligation-metadata
   #:smt-spec
   #:make-smt-spec
   #:smt-spec-id
   #:smt-spec-logic
   #:smt-spec-obligations
   #:smt-spec-source-path
   #:smt-spec-semantic-tags
   #:smt-spec-metadata
   #:compile-smt-obligation
   #:check-smt-obligation
   #:check-smt-spec
   #:summarize-smt-spec-results
   #:sweep-smt-spec-suite
   #:emit-smtlib-for-smt-spec
   #:emitted-smtlib-path-for-smt-spec
   #:check-emitted-smt-spec-parity
   #:compare-smt-spec-with-smtlib-file
   #:core-smt-obligation
   #:make-core-smt-obligation
   #:core-smt-obligation-id
   #:core-smt-obligation-label
   #:core-smt-obligation-logic
   #:core-smt-obligation-query
   #:core-smt-obligation-assertions
   #:core-smt-obligation-expected-status
   #:core-smt-obligation-source-ref
   #:core-smt-obligation-metadata
   #:core-smt-module
   #:make-core-smt-module
   #:core-smt-module-id
   #:core-smt-module-source-path
   #:core-smt-module-logic
   #:core-smt-module-obligations
   #:core-smt-module-metadata
   #:smt-spec->core-smt-module
   #:smtlib-forms->core-smt-module
   #:smtlib-file->core-smt-module
   #:check-core-smt-module
   #:compare-core-smt-modules
   #:make-stage1-heap-commit-smt-spec
   #:make-stage1-control-refinement-smt-spec
   #:make-stage1-env-walk-smt-spec
   #:make-payload-traversal-search-smt-spec
   #:make-g2cl-interlock-closure-smt-spec
   #:make-g2imm8-interlock-closure-smt-spec
   #:make-default-mir-smt-spec-suite
   #:smt-cnf
   #:smt-cnf-var-count
   #:smt-cnf-clauses
   #:smt-cnf-root-literal
   #:lower-smt-to-boolean-core
   #:compile-boolean-core-to-cnf
   #:compile-smt-to-cnf
   #:compile-boolean-core-to-cnf-with-assumptions
   #:compile-smt-to-cnf-with-assumptions
   #:eval-cnf
   #:smt-cnf-sat-bruteforce
   #:make-smt-cnf-bundle
   #:solve-cnf-under-assumptions-dpll
   #:smt-cnf-unsat-core
   #:solve-cnf-dpll
   #:bitblast-smt-term
   #:run-smt-check
   #:*stage1-concept-source-path*
   #:stage1-program
   #:stage1-program-source-path
   #:stage1-program-forms
   #:stage1-program-scenarios
   #:stage1-program-helper-set
   #:stage1-scenario
   #:stage1-scenario-name
   #:stage1-scenario-root
   #:stage1-scenario-source
   #:stage1-compiler-form
   #:stage1-compiler-form-name
   #:stage1-compiler-form-compiler-name
   #:stage1-compiler-form-accepted-source-family
   #:stage1-compiler-form-helper-set
   #:stage1-compiler-form-successor-form
   #:stage1-compiler-form-emit-again
   #:stage1-compiler-form-authority
   #:stage1-promotion
   #:stage1-promotion-lineage
   #:stage1-promotion-compiler
   #:stage1-promotion-descriptor
   #:stage1-promotion-next-compiler
   #:stage1-promotion-next-form
   #:stage1-promotion-emit-again
   #:stage1-promotion-authority
   #:stage1-property-certificate
   #:stage1-property-certificate-property-id
   #:stage1-property-certificate-scenario
   #:stage1-property-certificate-claim
   #:stage1-property-certificate-status
   #:stage1-property-certificate-evidence
   #:stage1-property-certificate-payload
   #:stage1-property-certificate-payload-digest
   #:stage1-claim
   #:stage1-claim-property-id
   #:stage1-claim-scenario
   #:stage1-claim-status
   #:stage1-claim-witness-kind
   #:stage1-claim-subject
   #:stage1-claim-facts
   #:stage1-concept-bundle
   #:stage1-concept-bundle-source-path
   #:stage1-concept-bundle-source-digest
   #:stage1-concept-bundle-program-digest
   #:stage1-concept-bundle-checker-lane
   #:stage1-concept-bundle-property-certificates
   #:stage1-concept-bundle-agreement-certificates
   #:ingest-stage1-concept-file
   #:stage1-find-form
   #:stage1-find-scenario
   #:stage1-program-wf-p
   #:stage1-reference-program-wf-p
   #:cegis-problem
   #:cegis-problem-id
   #:cegis-problem-family
   #:cegis-problem-max-iterations
   #:cegis-problem-metadata
   #:smt-cegis-problem
   #:make-smt-cegis-problem
   #:smt-cegis-problem-logic
   #:smt-cegis-problem-vars
   #:smt-cegis-problem-base-assumptions
   #:smt-cegis-problem-goal
   #:smt-cegis-problem-expected-status
   #:smt-cegis-problem-initial-constraints
   #:lsip-edge-policy-cegis-problem
   #:make-lsip-edge-policy-cegis-problem
   #:lsip-edge-policy-cegis-problem-edge-id
   #:lsip-edge-policy-cegis-problem-relation
   #:lsip-edge-policy-cegis-problem-required-obligation-classes
   #:lsip-edge-policy-cegis-problem-initial-law-ids
   #:lsip-edge-policy-cegis-problem-fallback-policy
   #:lsip-edge-policy-cegis-problem-evidence-threshold
   #:lsip-edge-policy-cegis-problem-expected-status
   #:compiler-mutation-cegis-problem
   #:make-compiler-mutation-cegis-problem
   #:compiler-mutation-cegis-problem-initial-payload
   #:compiler-mutation-cegis-problem-counterexamples
   #:compiler-mutation-cegis-problem-expected-status
   #:make-cegis-refinement-kind
   #:cegis-refinement-kind-id
   #:cegis-refinement-kind-family
   #:cegis-refinement-kind-counterexample-kind
   #:cegis-refinement-kind-replay-form
   #:cegis-refinement-kind-summary
   #:cegis-refinement-kind-terminalp
   #:cegis-refinement-kind-note
   #:cegis-family-manifest
   #:make-cegis-family-manifest
   #:cegis-family-manifest-id
   #:cegis-family-manifest-problem-type
   #:cegis-family-manifest-candidate-payload-schema
   #:cegis-family-manifest-counterexample-kinds
   #:cegis-family-manifest-refinement-kinds
   #:cegis-family-manifest-operation-id
   #:cegis-family-manifest-constraint-class
   #:cegis-family-manifest-accepted-statuses
   #:cegis-family-manifest-stuck-statuses
   #:cegis-family-manifest-note
   #:cegis-object
   #:make-cegis-object
   #:cegis-object-id
   #:cegis-object-family
   #:cegis-object-kind
   #:cegis-object-payload
   #:cegis-object-metadata
   #:cegis-space
   #:make-cegis-space
   #:cegis-space-id
   #:cegis-space-family
   #:cegis-space-candidate-schema
   #:cegis-space-constraint-schema
   #:cegis-space-refinement-kinds
   #:cegis-space-metadata
   #:cegis-obligation-class
   #:make-cegis-obligation-class
   #:cegis-obligation-class-id
   #:cegis-obligation-class-family
   #:cegis-obligation-class-lane
   #:cegis-obligation-class-predicate
   #:cegis-obligation-class-projection
   #:cegis-obligation-class-counterexample-shape
   #:cegis-obligation-class-refinement-action
   #:cegis-obligation-class-soundness-note
   #:cegis-obligation-class-metadata
   #:cegis-search-ir
   #:make-cegis-search-ir
   #:cegis-search-ir-id
   #:cegis-search-ir-family
   #:cegis-search-ir-candidate-schema
   #:cegis-search-ir-obligation-classes
   #:cegis-search-ir-projection-schema
   #:cegis-search-ir-replay-schema
   #:cegis-search-ir-metadata
   #:cegis-constraint
   #:make-cegis-constraint
   #:cegis-constraint-id
   #:cegis-constraint-family
   #:cegis-constraint-kind
   #:cegis-constraint-expression
   #:cegis-constraint-source
   #:cegis-constraint-metadata
   #:cegis-refinement-rule
   #:make-cegis-refinement-rule
   #:cegis-refinement-rule-id
   #:cegis-refinement-rule-family
   #:cegis-refinement-rule-kind
   #:cegis-refinement-rule-counterexample-kind
   #:cegis-refinement-rule-replay-form
   #:cegis-refinement-rule-terminalp
   #:cegis-refinement-rule-metadata
   #:cegis-evaluation
   #:make-cegis-evaluation
   #:cegis-evaluation-id
   #:cegis-evaluation-family
   #:cegis-evaluation-candidate
   #:cegis-evaluation-status
   #:cegis-evaluation-hard-failures
   #:cegis-evaluation-soft-failures
   #:cegis-evaluation-constraint-count
   #:cegis-evaluation-candidate-cost
   #:cegis-evaluation-novelty
   #:cegis-evaluation-score
   #:cegis-evaluation-evidence
   #:cegis-evaluation-metadata
   #:cegis-trace-step
   #:make-cegis-trace-step
   #:cegis-trace-step-id
   #:cegis-trace-step-iteration
   #:cegis-trace-step-candidate
   #:cegis-trace-step-check-summary
   #:cegis-trace-step-counterexample
   #:cegis-trace-step-refinement
   #:cegis-trace-step-next-candidate
   #:cegis-trace-step-evaluation
   #:cegis-trace-step-status
   #:cegis-trace-step-metadata
   #:cegis-trace
   #:make-cegis-trace
   #:cegis-trace-id
   #:cegis-trace-problem-id
   #:cegis-trace-family
   #:cegis-trace-status
   #:cegis-trace-steps
   #:cegis-trace-final-state
   #:cegis-trace-evaluation
   #:cegis-trace-metadata
   #:cegis-candidate
   #:make-cegis-candidate
   #:cegis-candidate-id
   #:cegis-candidate-family
   #:cegis-candidate-payload
   #:cegis-candidate-metadata
   #:cegis-counterexample
   #:make-cegis-counterexample
   #:cegis-counterexample-id
   #:cegis-counterexample-problem-id
   #:cegis-counterexample-family
   #:cegis-counterexample-kind
   #:cegis-counterexample-source-operation
   #:cegis-counterexample-failing-obligation
   #:cegis-counterexample-witness-kind
   #:cegis-counterexample-witness
   #:cegis-counterexample-replay-payload
   #:cegis-counterexample-diagnostics
   #:cegis-refinement
   #:make-cegis-refinement
   #:cegis-refinement-id
   #:cegis-refinement-problem-id
   #:cegis-refinement-kind
   #:cegis-refinement-payload
   #:cegis-refinement-replay-payload
   #:cegis-refinement-summary
   #:cegis-refinement-metadata
   #:cegis-step-result
   #:make-cegis-step-result
   #:cegis-step-result-iteration
   #:cegis-step-result-candidate
   #:cegis-step-result-check-result
   #:cegis-step-result-acceptedp
   #:cegis-step-result-counterexample
   #:cegis-step-result-refinement
   #:cegis-step-result-next-candidate
   #:cegis-step-result-status
   #:cegis-step-result-diagnostics
   #:cegis-run-state
   #:make-cegis-run-state
   #:cegis-run-state-problem-id
   #:cegis-run-state-iteration
   #:cegis-run-state-status
   #:cegis-run-state-current-candidate
   #:cegis-run-state-accepted-candidate
   #:cegis-run-state-history
   #:cegis-run-state-last-counterexample
   #:cegis-run-state-last-refinement
   #:cegis-run-state-max-iterations
   #:cegis-run-state-metadata
   #:propose-candidate
   #:check-candidate
   #:extract-counterexample
   #:refine-candidate
   #:accept-candidate-p
   #:list-cegis-refinement-kinds
   #:find-cegis-refinement-kind
   #:cegis-refinement-kind-object
   #:list-cegis-family-manifests
   #:find-cegis-family-manifest
   #:list-cegis-obligation-classes
   #:find-cegis-obligation-class
   #:cegis-obligation-class-object
   #:list-cegis-obligation-class-objects
   #:cegis-family-manifest-object
   #:list-cegis-family-manifest-objects
   #:list-cegis-spaces
   #:describe-cegis-space
   #:cegis-family-obligation-classes
   #:cegis-family-search-ir
   #:list-cegis-search-irs
   #:describe-cegis-search-ir
   #:make-cegis-normalized-score
   #:cegis-family-space
   #:cegis-candidate-object
   #:cegis-refinement-rule-object
   #:cegis-refinement-constraint
   #:apply-cegis-refinement
   #:make-initial-cegis-run-state
   #:run-cegis-step
   #:run-cegis-family
   #:run-smt-cegis
   #:run-lsip-edge-policy-cegis
   #:run-compiler-mutation-cegis
   #:cegis-step-result-score
   #:cegis-step-result-evaluation
   #:cegis-step-result-trace-step
   #:cegis-trace-from-run-state
   #:replay-cegis-trace
   #:run-cegis-step-artifact
   #:run-cegis-trace
   #:cegis-artifact-plist
   #:cegis-artifact-json-object
   #:cegis-artifact-from-plist
   #:cegis-artifact-from-json-object
   #:cegis-run-state-score
   #:cegis-run-state-evaluation
   #:summarize-cegis-run-state
   #:stage1-boot-scenario
   #:stage1-run-scenario
   #:stage1-promotion-summaries
   #:stage1-reference-promotion-summaries
   #:stage1-property-certificates
   #:stage1-reference-property-certificates
   #:stage1-agreement-certificates
   #:stage1-claim-summary
   #:stage1-d-claim
   #:emit-stage1-concept-bundle
   #:verify-stage1-concept-bundle
   #:admit-stage1-concept-program
   #:check-stage1-concept-closure
   #:kernel-implementation
   #:kernel-implementation-id
   #:native-kernel-implementation
   #:current-kernel-implementation
   #:call-with-kernel-implementation
   #:with-kernel-implementation
   #:make-defir-kernel-implementation
   #:make-ingested-lean-def-kernel-implementation
   #:make-ingested-lean-whnf-kernel-implementation
   #:make-kernel-family-ingested-algorithm
   #:make-smt-family-ingested-algorithm
   #:make-stage1-family-ingested-algorithm
   #:initialize-ingested-algorithm-registry
   #:make-reference-kernel-implementation
   #:shift
   #:subst
   #:subst-top
   #:whnf
   #:conv?
   #:infer
   #:check
   #:normalize-smt-term-defir
   #:lower-smt-to-boolean-core-defir
   #:compile-boolean-core-to-cnf-defir
   #:compile-boolean-core-to-cnf-with-assumptions-defir
   #:bitblast-smt-term-defir
   #:compile-smt-to-cnf-defir
   #:compile-smt-to-cnf-with-assumptions-defir
   #:solve-cnf-dpll-defir
   #:solve-cnf-under-assumptions-dpll-defir
   #:run-demo))

(defpackage :mini-kernel-reference
  (:use :cl)
  (:export
   #:make-reference-env
   #:validate-certificate
   #:check-certificate))

(defpackage :mini-kernel-corpus
  (:use :cl)
  (:export
   #:corpus-entry
   #:corpus-entry-id
   #:corpus-entry-certificate
   #:accepted-certificates
   #:rejected-certificates
   #:malformed-certificates
   #:generated-certificates
   #:generated-corpus-report
   #:render-generated-corpus-report
   #:write-generated-corpus-report))

(in-package :mini-kernel)

(declaim (ftype function whnf infer check))

(define-condition kernel-error (error)
  ((message :initarg :message :reader kernel-error-message))
  (:report (lambda (condition stream)
             (princ (kernel-error-message condition) stream))))

(defun kernel-error (format-string &rest args)
  (error 'kernel-error :message (apply #'format nil format-string args)))
