(in-package :mini-kernel)

(defun smtlib-symbol= (symbol name)
  (and (symbolp symbol)
       (string= (symbol-name symbol) name)))

(defun %make-smtlib-const-entry (sort)
  (list :const sort))

(defun %make-smtlib-term-entry (term sort)
  (list :term term sort))

(defun %make-smtlib-define-entry (params result-sort body)
  (list :define params result-sort body))

(defun %smtlib-entry-kind (entry)
  (and (consp entry) (first entry)))

(defun %smtlib-entry-sort (entry)
  (case (%smtlib-entry-kind entry)
    (:const (second entry))
    (:term (third entry))
    (:define (third entry))
    (otherwise
     (kernel-error "invalid SMT-LIB environment entry: ~S" entry))))

(defun %copy-smtlib-env (env)
  (let ((copy (make-hash-table :test #'eq)))
    (maphash (lambda (key value)
               (setf (gethash key copy) value))
             env)
    copy))

(defun %smtlib-bv-sort-p (sort)
  (eq (smt-sort-kind sort) :BV))

(defun %smtlib-int-sort-p (sort)
  (eq (smt-sort-kind sort) :Int))

(defun %smtlib-bv-width (sort)
  (unless (%smtlib-bv-sort-p sort)
    (kernel-error "expected bitvector sort, got ~S" sort))
  (second sort))

(defun %smtlib-ast-sort (term)
  (case (smt-tag term)
    (:bool (smt-bool-sort))
    (:var (third term))
    (:int-lit (smt-int-sort))
    (:bv-lit (smt-bv-sort (second term)))
    ((:not :and :or :xor :=> := :ult)
     (smt-bool-sort))
    (:ite
     (%smtlib-ast-sort (third term)))
    ((:bvnot :bvand :bvor :bvxor :bvadd :bvsub :bvshl)
     (%smtlib-ast-sort (second term)))
    ((:int-add :int-sub :int-mod)
     (smt-int-sort))
    ((:int-lt :int-le :int-gt :int-ge)
     (smt-bool-sort))
    (:concat
     (let ((lhs-sort (%smtlib-ast-sort (second term)))
           (rhs-sort (%smtlib-ast-sort (third term))))
       (smt-bv-sort (+ (%smtlib-bv-width lhs-sort)
                       (%smtlib-bv-width rhs-sort)))))
    (:extract
     (smt-bv-sort (1+ (- (second term) (third term)))))
    (otherwise
     (kernel-error "cannot infer sort for SMT AST: ~S" term))))

(defun smtlib-sort->sort (form)
  (cond
    ((smtlib-symbol= form "BOOL")
     (smt-bool-sort))
    ((smtlib-symbol= form "INT")
     (smt-int-sort))
    ((and (consp form)
          (smtlib-symbol= (first form) "_")
          (smtlib-symbol= (second form) "BITVEC")
          (integerp (third form))
          (plusp (third form)))
     (smt-bv-sort (third form)))
    (t
     (kernel-error "unsupported SMT-LIB sort: ~S" form))))

(defun %smtlib-literal->ast (form expected-sort)
  (cond
    ((integerp form)
     (if (%smtlib-bv-sort-p expected-sort)
         (smt-bv-lit (%smtlib-bv-width expected-sort) form)
         (if (%smtlib-int-sort-p expected-sort)
             (smt-int-lit form)
             (kernel-error "unsupported SMT-LIB numeric atom ~S with expected sort ~S"
                           form
                           expected-sort))))
    (t
     (kernel-error "unsupported SMT-LIB atom: ~S" form))))

(defun %smtlib-ensure-same-sort (lhs rhs)
  (let ((lhs-sort (%smtlib-ast-sort lhs))
        (rhs-sort (%smtlib-ast-sort rhs)))
    (unless (equal lhs-sort rhs-sort)
      (kernel-error "SMT-LIB operands must have the same sort, got ~S and ~S"
                    lhs-sort
                    rhs-sort))
    lhs-sort))

(defun %smtlib-parse-same-sort-binary (lhs-form rhs-form env &optional expected-sort)
  (cond
    ((and (integerp lhs-form) (integerp rhs-form))
     (unless expected-sort
       (kernel-error "cannot infer sort for SMT-LIB literal pair: ~S and ~S"
                     lhs-form
                     rhs-form))
     (let ((lhs (smtlib-term->ast lhs-form env expected-sort))
           (rhs (smtlib-term->ast rhs-form env expected-sort)))
       (%smtlib-ensure-same-sort lhs rhs)
       (values lhs rhs expected-sort)))
    ((integerp lhs-form)
     (let* ((rhs (smtlib-term->ast rhs-form env expected-sort))
            (sort (%smtlib-ast-sort rhs))
            (lhs (smtlib-term->ast lhs-form env sort)))
       (%smtlib-ensure-same-sort lhs rhs)
       (values lhs rhs sort)))
    ((integerp rhs-form)
     (let* ((lhs (smtlib-term->ast lhs-form env expected-sort))
            (sort (%smtlib-ast-sort lhs))
            (rhs (smtlib-term->ast rhs-form env sort)))
       (%smtlib-ensure-same-sort lhs rhs)
       (values lhs rhs sort)))
    (t
     (let* ((lhs (smtlib-term->ast lhs-form env expected-sort))
            (sort (%smtlib-ast-sort lhs))
            (rhs (smtlib-term->ast rhs-form env sort)))
       (%smtlib-ensure-same-sort lhs rhs)
       (values lhs rhs sort)))))

(defun %smtlib-lower-bvshl (lhs rhs)
  (unless (eq (smt-tag rhs) :bv-lit)
    (kernel-error "only literal bvshl amounts are supported in SMT-LIB ingestion, got ~S"
                  rhs))
  (let* ((lhs-sort (%smtlib-ast-sort lhs))
         (width (%smtlib-bv-width lhs-sort))
         (shift (smt-bv-value rhs)))
    (cond
      ((zerop shift) lhs)
      ((>= shift width) (smt-bv-lit width 0))
      (t
       (smt-concat
        (smt-extract (- width shift 1) 0 lhs)
        (smt-bv-lit shift 0))))))

(defun %smtlib-lower-distinct (args env &optional expected-sort)
  (unless (>= (length args) 2)
    (kernel-error "SMT-LIB DISTINCT expects at least two arguments, got ~D"
                  (length args)))
  (let ((terms (mapcar (lambda (arg)
                         (smtlib-term->ast arg env expected-sort))
                       args)))
    (loop for rest on terms
          while (rest rest)
          do (%smtlib-ensure-same-sort (first rest) (second rest)))
    (let ((clauses '()))
      (loop for left-rest on terms
            while (rest left-rest)
            do (dolist (rhs (rest left-rest))
                 (%smtlib-ensure-same-sort (first left-rest) rhs)
                 (push (smt-not (smt-eq (first left-rest) rhs)) clauses)))
      (apply #'smt-and (nreverse clauses)))))

(defun %smtlib-apply-defined-function (entry arg-forms env)
  (let ((params (second entry))
        (result-sort (third entry))
        (body (fourth entry)))
    (unless (= (length params) (length arg-forms))
      (kernel-error "SMT-LIB define-fun arity mismatch, expected ~D args and got ~D"
                    (length params)
                    (length arg-forms)))
    (let ((local-env (%copy-smtlib-env env)))
      (loop for param in params
            for arg-form in arg-forms
            do (destructuring-bind (name sort) param
                 (setf (gethash name local-env)
                       (%make-smtlib-term-entry
                        (smtlib-term->ast arg-form env sort)
                        sort))))
      (smtlib-term->ast body local-env result-sort))))

(defun smtlib-term->ast (form env &optional expected-sort)
  (cond
    ((smtlib-symbol= form "TRUE")
     (smt-bool-const t))
    ((smtlib-symbol= form "FALSE")
     (smt-bool-const nil))
    ((integerp form)
     (%smtlib-literal->ast form expected-sort))
    ((symbolp form)
     (let ((entry (gethash form env)))
       (unless entry
         (kernel-error "undeclared SMT-LIB symbol: ~S" form))
       (case (%smtlib-entry-kind entry)
         (:term (second entry))
         (:const (smt-var form (second entry)))
         (:define
          (if (null (second entry))
              (smtlib-term->ast (fourth entry) env (third entry))
              (kernel-error "SMT-LIB function ~S requires arguments" form)))
         (otherwise
          (kernel-error "invalid SMT-LIB environment entry: ~S" entry)))))
    ((consp form)
     (cond
       ((and (consp (first form))
             (smtlib-symbol= (first (first form)) "_")
             (smtlib-symbol= (second (first form)) "ZERO_EXTEND")
             (integerp (third (first form)))
             (= (length form) 2))
        (let* ((amount (third (first form)))
               (inner (smtlib-term->ast (second form) env)))
          (unless (%smtlib-bv-sort-p (%smtlib-ast-sort inner))
            (kernel-error "zero_extend expects a bitvector term, got ~S" inner))
          (smt-concat (smt-bv-lit amount 0) inner)))
       ((smtlib-symbol= (first form) "NOT")
        (smt-not (smtlib-term->ast (second form) env (smt-bool-sort))))
       ((smtlib-symbol= (first form) "AND")
        (apply #'smt-and
               (mapcar (lambda (term)
                         (smtlib-term->ast term env (smt-bool-sort)))
                       (rest form))))
       ((smtlib-symbol= (first form) "OR")
        (apply #'smt-or
               (mapcar (lambda (term)
                         (smtlib-term->ast term env (smt-bool-sort)))
                       (rest form))))
       ((smtlib-symbol= (first form) "=>")
        (smt-implies (smtlib-term->ast (second form) env (smt-bool-sort))
                     (smtlib-term->ast (third form) env (smt-bool-sort))))
       ((smtlib-symbol= (first form) "=")
        (multiple-value-bind (lhs rhs)
            (%smtlib-parse-same-sort-binary (second form) (third form) env expected-sort)
          (smt-eq lhs rhs)))
       ((smtlib-symbol= (first form) "DISTINCT")
        (%smtlib-lower-distinct (rest form) env expected-sort))
       ((smtlib-symbol= (first form) "ITE")
        (let ((condition (smtlib-term->ast (second form) env (smt-bool-sort))))
          (multiple-value-bind (then-branch else-branch)
              (%smtlib-parse-same-sort-binary (third form) (fourth form) env expected-sort)
            (smt-ite condition then-branch else-branch))))
       ((smtlib-symbol= (first form) "+")
        (apply #'smt-int-add
               (mapcar (lambda (term)
                         (smtlib-term->ast term env (smt-int-sort)))
                       (rest form))))
       ((smtlib-symbol= (first form) "-")
        (if (= (length form) 2)
            (smt-int-sub (smt-int-lit 0)
                         (smtlib-term->ast (second form) env (smt-int-sort)))
            (smt-int-sub (smtlib-term->ast (second form) env (smt-int-sort))
                         (smtlib-term->ast (third form) env (smt-int-sort)))))
       ((smtlib-symbol= (first form) "MOD")
        (smt-int-mod (smtlib-term->ast (second form) env (smt-int-sort))
                     (smtlib-term->ast (third form) env (smt-int-sort))))
       ((smtlib-symbol= (first form) "<")
        (smt-int-lt (smtlib-term->ast (second form) env (smt-int-sort))
                    (smtlib-term->ast (third form) env (smt-int-sort))))
       ((smtlib-symbol= (first form) "<=")
        (smt-int-le (smtlib-term->ast (second form) env (smt-int-sort))
                    (smtlib-term->ast (third form) env (smt-int-sort))))
       ((smtlib-symbol= (first form) ">")
        (smt-int-gt (smtlib-term->ast (second form) env (smt-int-sort))
                    (smtlib-term->ast (third form) env (smt-int-sort))))
       ((smtlib-symbol= (first form) ">=")
        (smt-int-ge (smtlib-term->ast (second form) env (smt-int-sort))
                    (smtlib-term->ast (third form) env (smt-int-sort))))
       ((smtlib-symbol= (first form) "BVADD")
        (multiple-value-bind (lhs rhs)
            (%smtlib-parse-same-sort-binary (second form) (third form) env expected-sort)
          (smt-bvadd lhs rhs)))
       ((smtlib-symbol= (first form) "BVSUB")
        (multiple-value-bind (lhs rhs)
            (%smtlib-parse-same-sort-binary (second form) (third form) env expected-sort)
          (smt-bvsub lhs rhs)))
       ((smtlib-symbol= (first form) "BVOR")
        (multiple-value-bind (lhs rhs)
            (%smtlib-parse-same-sort-binary (second form) (third form) env expected-sort)
          (smt-bvor lhs rhs)))
       ((smtlib-symbol= (first form) "BVAND")
        (multiple-value-bind (lhs rhs)
            (%smtlib-parse-same-sort-binary (second form) (third form) env expected-sort)
          (smt-bvand lhs rhs)))
       ((smtlib-symbol= (first form) "BVXOR")
        (multiple-value-bind (lhs rhs)
            (%smtlib-parse-same-sort-binary (second form) (third form) env expected-sort)
          (smt-bvxor lhs rhs)))
       ((smtlib-symbol= (first form) "BVSHL")
        (multiple-value-bind (lhs rhs)
            (%smtlib-parse-same-sort-binary (second form) (third form) env expected-sort)
          (%smtlib-lower-bvshl lhs rhs)))
       ((smtlib-symbol= (first form) "BVULE")
        (multiple-value-bind (lhs rhs)
            (%smtlib-parse-same-sort-binary (second form) (third form) env expected-sort)
          (smt-or (smt-eq lhs rhs)
                  (smt-ult lhs rhs))))
       ((smtlib-symbol= (first form) "CONCAT")
        (let ((lhs (smtlib-term->ast (second form) env))
              (rhs (smtlib-term->ast (third form) env)))
          (unless (%smtlib-bv-sort-p (%smtlib-ast-sort lhs))
            (kernel-error "concat expects bitvector lhs, got ~S" lhs))
          (unless (%smtlib-bv-sort-p (%smtlib-ast-sort rhs))
            (kernel-error "concat expects bitvector rhs, got ~S" rhs))
          (smt-concat lhs rhs)))
       ((smtlib-symbol= (first form) "EXTRACT")
        (smt-extract (second form)
                     (third form)
                     (smtlib-term->ast (fourth form) env)))
       (t
        (let ((entry (and (symbolp (first form))
                          (gethash (first form) env))))
          (if (and entry (eq (%smtlib-entry-kind entry) :define))
              (%smtlib-apply-defined-function entry (rest form) env)
              (kernel-error "unsupported SMT-LIB term: ~S" form))))))
    (t
     (kernel-error "unsupported SMT-LIB atom: ~S" form))))

(defun read-smtlib-forms (path)
  (with-open-file (stream path :direction :input)
    (loop for form = (read stream nil :eof)
          until (eq form :eof)
          collect form)))

(defun %current-smtlib-assertions (stack)
  (if stack
      (first stack)
      (kernel-error "empty SMT-LIB assertion stack")))

(defun %conjoin-smt-assertions (assertions)
  (cond
    ((null assertions) (smt-bool-const t))
    ((null (rest assertions)) (first assertions))
    (t (apply #'smt-and (reverse assertions)))))

(defun run-smtlib-commands (store forms)
  (let ((env (make-hash-table :test #'eq))
        (stack (list '()))
        (current-label nil)
        (results '()))
    (dolist (form forms)
      (cond
        ((smtlib-symbol= (first form) "SET-LOGIC")
         nil)
        ((smtlib-symbol= (first form) "DECLARE-CONST")
         (setf (gethash (second form) env)
               (%make-smtlib-const-entry
                (smtlib-sort->sort (third form)))))
        ((smtlib-symbol= (first form) "DECLARE-FUN")
         (unless (null (third form))
           (kernel-error "only nullary DECLARE-FUN is supported in SMT-LIB ingestion: ~S"
                         form))
         (setf (gethash (second form) env)
               (%make-smtlib-const-entry
                (smtlib-sort->sort (fourth form)))))
        ((smtlib-symbol= (first form) "DEFINE-FUN")
         (let ((name (second form))
               (params (third form))
               (result-sort (smtlib-sort->sort (fourth form)))
               (body (fifth form)))
           (setf (gethash name env)
                 (%make-smtlib-define-entry
                  (mapcar (lambda (param)
                            (list (first param)
                                  (smtlib-sort->sort (second param))))
                          params)
                  result-sort
                  body))))
        ((smtlib-symbol= (first form) "ASSERT")
         (push (smtlib-term->ast (second form) env (smt-bool-sort))
               (first stack)))
        ((smtlib-symbol= (first form) "ECHO")
         (setf current-label (second form)))
        ((smtlib-symbol= (first form) "PUSH")
         (push (copy-list (%current-smtlib-assertions stack)) stack))
        ((smtlib-symbol= (first form) "POP")
         (when (null (rest stack))
           (kernel-error "SMT-LIB pop underflow"))
         (pop stack))
        ((smtlib-symbol= (first form) "CHECK-SAT")
         (let* ((formula (%conjoin-smt-assertions (%current-smtlib-assertions stack)))
                (result (run-smt-check store formula)))
           (push (list :label current-label
                       :status (backend-result-status result)
                       :evidence (backend-result-evidence result)
                       :result result)
                 results)))
        ((or (smtlib-symbol= (first form) "GET-MODEL")
             (smtlib-symbol= (first form) "GET-UNSAT-CORE"))
         nil)
        (t
         (kernel-error "unsupported SMT-LIB command: ~S" form))))
    (nreverse results)))

(defun run-smtlib-file (store path)
  (run-smtlib-commands store (read-smtlib-forms path)))

(defun summarize-smtlib-results (results)
  (let ((accepted 0)
        (rejected 0)
        (unknown 0)
        (labels '()))
    (dolist (entry results)
      (push (getf entry :label) labels)
      (case (getf entry :status)
        (:accepted (incf accepted))
        (:rejected (incf rejected))
        (:unknown (incf unknown))))
    (list :total (length results)
          :accepted accepted
          :rejected rejected
          :unknown unknown
          :labels (nreverse labels))))

(defun summarize-smtlib-file (path &optional (store (make-advisory-store)))
  (let ((results (run-smtlib-file store path)))
    (list :path path
          :summary (summarize-smtlib-results results)
          :results results)))

(defun sweep-smtlib-directory (directory-pattern &key sortp)
  (let* ((paths (directory directory-pattern))
         (ordered (if sortp
                      (sort (copy-list paths) #'string< :key #'namestring)
                      paths))
         (entries '())
         (accepted 0)
         (rejected 0)
         (unknown 0)
         (checks 0))
    (dolist (path ordered)
      (let* ((summary-entry (summarize-smtlib-file (namestring path)))
             (summary (getf summary-entry :summary)))
        (incf accepted (getf summary :accepted))
        (incf rejected (getf summary :rejected))
        (incf unknown (getf summary :unknown))
        (incf checks (getf summary :total))
        (push summary-entry entries)))
    (list :pattern directory-pattern
          :files (length ordered)
          :checks checks
          :accepted accepted
          :rejected rejected
          :unknown unknown
          :entries (nreverse entries))))
